Repository opensearch-project/opensearch-dashboards-functional-test, pull requests merged in 2022-04, with the labels that each got.

#157 [CI] build TEST_FILES for CI based on build manifest
  integtest.sh
  test_finder.sh
Labels: backport 1.x, backport 1.3

#164 [Security] fix tests that failed on ARM64
  cypress/integration/plugins/security/audit_log_spec.js
  cypress/integration/plugins/security/get_started_spec.js
  cypress/integration/plugins/security/permissions_spec.js
Labels: backport 1.x, backport 1.3, 1.3.1

#166 [Docs] backport port process
  CONTRIBUTING.md
Labels: documentation

#165 Version bump to 1.3.1
  package-lock.json
  package.json
Labels: 1.3.1

#172 [AD] Test improvements to check if item exist
  cypress/integration/plugins/anomaly-detection-dashboards-plugin/dashboard_spec.js
  cypress/integration/plugins/anomaly-detection-dashboards-plugin/detector_list_spec.js
  cypress/integration/plugins/anomaly-detection-dashboards-plugin/real_time_results_spec.js
Labels: backport 1.x, backport 1.3, 1.3.1

#175 [ISM] show all rows for test
  cypress/integration/plugins/index-management-dashboards-plugin/indices_spec.js
Labels: backport 1.x, backport 1.3

#185 [Notifications] onboard sanity tests for notifications plugin
  .github/workflows/notifications-release-e2e-workflow.yml
  cypress/integration/plugins/notifications-dashboards/channels.spec.js
  cypress/integration/plugins/notifications-dashboards/dashboard.spec.js
  cypress/integration/plugins/notifications-dashboards/email_groups.spec.js
  cypress/utils/constants.js
  cypress/utils/plugins/notifications-dashboards/constants.js
  test_finder.sh
Labels: 2.0.0

#209 Lock Cypress version to 9.5.4 so it will not use other versions
  package-lock.json
  package.json
Labels: bug
