Repository opensearch-project/opensearch-dashboards-functional-test, pull requests merged in 2022-10, with the labels that each got.

#325 [MD] func testing for data source management listing
  .github/workflows/cypress-workflow-bundle-snapshot-based.yml
  cypress.json
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/datasource-management-plugin/2_datasource_table.spec.js
  cypress/support/index.js
  cypress/utils/dashboards/datasource-management-dashboards-plugin/commands.js
  cypress/utils/dashboards/datasource-management-dashboards-plugin/constants.js
Labels: backport 2.x, v2.4.0

#316 [MD] functional test for datasource creation page
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/datasource-management-plugin/1_create_datasource.spec.js
  cypress/utils/dashboards/datasource-management-dashboards-plugin/cosntants.js
Labels: backport 2.x, v2.4.0

#341 [MD] datasource edit/update page functional tests
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/datasource-management-plugin/1_create_datasource.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/datasource-management-plugin/2_datasource_table.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/datasource-management-plugin/3_update_datasource.spec.js
  cypress/utils/dashboards/datasource-management-dashboards-plugin/constants.js
  cypress/utils/dashboards/datasource-management-dashboards-plugin/cosntants.js
Labels: backport 2.x, v2.4.0

#334 Add test for aggregation view feature
  cypress.json
  cypress/fixtures/plugins/security-dashboards-plugin/indexpatterns/indexPatternTenantHeader.json
  cypress/fixtures/plugins/security-dashboards-plugin/roles/roleWithTest.json
  cypress/fixtures/plugins/security-dashboards-plugin/roles/roleWithoutTest.json
  cypress/fixtures/plugins/security-dashboards-plugin/rolesmapping/kibanauserRoleMapping.json
  cypress/fixtures/plugins/security-dashboards-plugin/rolesmapping/roleWithTestMapping.json
  cypress/fixtures/plugins/security-dashboards-plugin/rolesmapping/roleWithoutTestMapping.json
  cypress/fixtures/plugins/security-dashboards-plugin/tenants/testTenant.json
  cypress/fixtures/plugins/security-dashboards-plugin/users/testUser.json
  cypress/integration/plugins/security-dashboards-plugin/aggregation_view.js
  cypress/support/index.js
  cypress/utils/commands.js
  cypress/utils/constants.js
  cypress/utils/dashboards/constants.js
  cypress/utils/index.d.ts
  cypress/utils/plugins/security-dashboards-plugin/commands.js
  cypress/utils/plugins/security-dashboards-plugin/constants.js
  cypress/utils/plugins/security-dashboards-plugin/index.d.ts
  cypress/utils/plugins/security/constants.js
  package.json
Labels: backport 2.x

#344 [MD] Update DS list page FT based on UX change
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/datasource-management-plugin/2_datasource_table.spec.js
Labels: enhancement, backport 2.x, v2.4.0

#343 [MD] update functional tests on edit/update datasource as per UX changes
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/datasource-management-plugin/3_update_datasource.spec.js
Labels: enhancement, backport 2.x, v2.4.0

#354 [Security] Bump minimatch to 3.1.2 to fix the ReDoS vulnerability
  package-lock.json
Labels: backport 1.x, backport 2.x
