Repository opensearch-project/opensearch-dashboards-functional-test, pull requests merged in 2022-09, with the labels that each got.

#287 update version to be 2.4.0
  package.json
Labels: v2.3.0

#292 Clean up create detector AD test
  cypress/integration/plugins/anomaly-detection-dashboards-plugin/create_detector_spec.js
Labels: backport 2.x

#295 Change form:false for AD request
  cypress/integration/plugins/anomaly-detection-dashboards-plugin/create_detector_spec.js
Labels: backport 1.x, backport 1.3, backport 2.x, backport 2.0, backport 1.2, backport 1.1, backport 1.0, backport 2.2, backport 2.3, backport 2.1
