Repository opensearch-project/opensearch-dashboards-functional-test, pull requests merged in 2022-11, with the labels that each got.

#361 [Vis Builder] Updates tests to visBuilder key
  .github/workflows/cypress-workflow-bundle-snapshot-based.yml
  CONTRIBUTING.md
  cypress/fixtures/dashboard/opensearch_dashboards/visBuilder/vb_saved_objects.ndjson
  cypress/fixtures/dashboard/opensearch_dashboards/visBuilder/vis-builder.data.txt
  cypress/fixtures/dashboard/opensearch_dashboards/visBuilder/vis_builder.data.txt
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/basic.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/dashboard.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/experimental.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/area.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/bar.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/line.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/metric.spec.js
  cypress/utils/dashboards/commands.js
  cypress/utils/dashboards/index.d.ts
  cypress/utils/dashboards/vis_builder/constants.js
Labels: backport 2.x, v2.4.0

#357 Add test cases for filter of aggregation view feature
  cypress/integration/plugins/security-dashboards-plugin/aggregation_view.js
Labels: backport 2.x, backport 2.4

#362 Add integration test for Search Relevance Dashboards
  .github/workflows/search-relevance-release-e2e-workflow.yml
  cypress/integration/plugins/search-relevance-dashboards/1_query_compare.spec.js
  cypress/utils/plugins/search-relevance-dashboards/constants.js
  test_finder.sh
Labels: backport 2.x, v2.4.0, backport 2.4

#372 [VisBuilder] Allow rounding errors
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/area.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/bar.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/line.spec.js
Labels: backport 2.x, backport 2.4

#376 Enables visbuilder tests by default
  cypress.json
Labels: backport 2.x, backport 2.4

#367 Add Windows workflow on cypress bundle build
  .github/workflows/cypress-workflow-bundle-snapshot-based-windows.yml
  .github/workflows/release-e2e-workflow-template-windows.yml
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/dashboard_sanity_test_spec.js
  test_finder.sh
Labels: enhancement, windows

#380 Onboarding security analytics dashboards plugin.
  .github/workflows/security-analytics-release-e2e-workflow.yml
  cypress/integration/plugins/security-analytics-dashboards-plugin/rules_spec.js
  cypress/support/index.js
  cypress/utils/constants.js
  cypress/utils/plugins/security-analytics-dashboards-plugin/commands.js
  cypress/utils/plugins/security-analytics-dashboards-plugin/constants.js
  site/index.html
  site/js/dashboard.js
  test_finder.sh
Labels: backport 2.4

#383 Add support for linux e2e template to run no-sec tests
  .github/workflows/cypress-workflow-bundle-snapshot-based-windows.yml
  .github/workflows/cypress-workflow-bundle-snapshot-based.yml
  .github/workflows/release-e2e-workflow-template-windows.yml
  .github/workflows/release-e2e-workflow-template.yml
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/dashboard_sanity_test_spec.js
Labels: enhancement, backport 2.x, backport 2.4

#385 [Backport 2.x] Add support for linux e2e template to run no-sec tests (#367 #383)
  .github/workflows/cypress-workflow-bundle-snapshot-based-windows.yml
  .github/workflows/cypress-workflow-bundle-snapshot-based.yml
  .github/workflows/release-e2e-workflow-template-windows.yml
  .github/workflows/release-e2e-workflow-template.yml
  test_finder.sh
Labels: backport 2.4, windows

#389 [Vis Builder] [Test] Add functional tests for table vis
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/table.spec.js
Labels: backport 2.x, v2.5.0

#395 add ashwin-pc to maintainers
  MAINTAINERS.md
Labels: backport 1.x, backport 1.3, backport 2.x, backport 2.4
