Repository opensearch-project/opensearch-dashboards-functional-test, pull requests merged in 2023-06, with the labels that each got.

#718 [Admin] add ananzh as maintainer
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: backport 1.x, backport 2.x

#724 Add Prudhvi as new functional test repo maintainer
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: documentation

#719 Bump version to 2.8.1
  package.json
Labels: v2.8.1

#720 Bump version to 2.9
  package.json
Labels: v2.9.0
