Repository opensearch-project/opensearch-dashboards-functional-test, pull requests merged in 2023-10, with the labels that each got.

#909 Workbench updates to remove title checks
  cypress/integration/plugins/query-workbench-dashboards/ui.spec.js
Labels: backport 2.x, v2.11.0, backport 2.11

#908 [bug] update installation commands in DEVELOPER_GUIDE.md
  DEVELOPER_GUIDE.md
Labels: backport 2.x

#736 Tenant change related integration tests - allow tenant change and retain tenant in shortlink
  cypress/integration/plugins/security-dashboards-plugin/change_tenant_successfully.js
  cypress/integration/plugins/security-dashboards-plugin/switch_tenant.js
  cypress/integration/plugins/security-dashboards-plugin/tenancy_change_on_shortlink.js
  cypress/utils/commands.js
  cypress/utils/index.d.ts
Labels: backport 2.x, v2.10.0

#919 [Backport 2.11] Security analytics latest tests (#825)
  cypress/integration/plugins/security-analytics-dashboards-plugin/1_detectors.spec.js
  cypress/integration/plugins/security-analytics-dashboards-plugin/2_rules.spec.js
  cypress/integration/plugins/security-analytics-dashboards-plugin/3_alerts.spec.js
  cypress/integration/plugins/security-analytics-dashboards-plugin/4_findings.spec.js
  cypress/utils/plugins/security-analytics-dashboards-plugin/commands.js
  cypress/utils/plugins/security-analytics-dashboards-plugin/constants.js
  cypress/utils/plugins/security-analytics-dashboards-plugin/index.d.ts
Labels: backport 2.x

#918 Fix flaky observability/4_panels tests
  cypress/integration/plugins/observability-dashboards/4_panels.spec.js
  cypress/utils/plugins/observability-dashboards/constants.js
Labels: backport 2.x, backport main, v2.11.0

#925 Update Observability event analytics visualization test
  cypress/integration/plugins/observability-dashboards/5_event_analytics.spec.js
Labels: backport 2.x, backport main

#936 Add wait time after selecting a color
  cypress/integration/plugins/custom-import-map-dashboards/documentsLayer.spec.js
Labels: backport 2.x, backport 2.11

#939 removed observability tests that can be run locally
  cypress/integration/plugins/observability-dashboards/1_trace_analytics_dashboard.spec.js
  cypress/integration/plugins/observability-dashboards/2_trace_analytics_services.spec.js
  cypress/integration/plugins/observability-dashboards/3_trace_analytics_traces.spec.js
  cypress/integration/plugins/observability-dashboards/4_panels.spec.js
  cypress/integration/plugins/observability-dashboards/5_event_analytics.spec.js
  cypress/integration/plugins/observability-dashboards/6_notebooks.spec.js
  cypress/integration/plugins/observability-dashboards/7_app_analytics.spec.js
Labels: backport 2.x, v2.12.0
