Repository opensearch-project/opensearch-dashboards-functional-test, pull requests merged in 2023-01, with the labels that each got.

#436 Add new tests to custom-import-map
  cypress/integration/plugins/custom-import-map-dashboards/documentsLayer.spec.js
  cypress/integration/plugins/custom-import-map-dashboards/opensearchMapLayer.spec.js
Labels: backport 2.x, backport 2.5

#440 [BUG] Fix multiple submit bug
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/datasource-management-plugin/1_create_datasource.spec.js
Labels: bug

#442 feat: add function test for IM plugin on v2.5
  cypress/integration/plugins/index-management-dashboards-plugin/aliases.js
  cypress/integration/plugins/index-management-dashboards-plugin/create_index.js
  cypress/integration/plugins/index-management-dashboards-plugin/indices_spec.js
  cypress/integration/plugins/index-management-dashboards-plugin/reindex_spec.js
  cypress/integration/plugins/index-management-dashboards-plugin/snapshots_spec.js
  cypress/integration/plugins/index-management-dashboards-plugin/split_index.js
  cypress/integration/plugins/index-management-dashboards-plugin/templates.js
  cypress/utils/plugins/index-management-dashboards-plugin/commands.js
Labels: backport 2.5

#399 Update observability tests
  cypress/integration/plugins/observability-dashboards/0_before.spec.js
  cypress/integration/plugins/observability-dashboards/2_trace_analytics_services.spec.js
  cypress/integration/plugins/observability-dashboards/4_panels.spec.js
  cypress/integration/plugins/observability-dashboards/5_event_analytics.spec.js
  cypress/integration/plugins/observability-dashboards/7_app_analytics.spec.js
  cypress/utils/plugins/observability-dashboards/constants.js
Labels: backport 2.x, backport 2.5

#450 feat: remove snapshot_spec and duplicate commands
  cypress/integration/plugins/index-management-dashboards-plugin/aliases.js
  cypress/integration/plugins/index-management-dashboards-plugin/snapshots_spec.js
  cypress/utils/plugins/index-management-dashboards-plugin/commands.js
Labels: backport 2.5

#424 Removing form field in gantt-chart, observability and workbench
  cypress/integration/plugins/gantt-chart-dashboards/gantt_ui.spec.js
  cypress/integration/plugins/observability-dashboards/0_before.spec.js
  cypress/integration/plugins/query-workbench-dashboards/ui.spec.js
Labels: backport 1.x, backport 1.3, backport 2.x, backport 2.0, backport 2.2, backport 2.3, backport 2.1, backport 2.4
