Repository opensearch-project/opensearch-dashboards-functional-test, pull requests merged in 2023-07, with the labels that each got.

#727 [Feature Anywhere / Vis Augmenter] Add test flows for integration with AD plugin
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis-augmenter/dashboard_spec.js
  cypress/integration/plugins/anomaly-detection-dashboards-plugin/sample_detector_spec.js
  cypress/integration/plugins/anomaly-detection-dashboards-plugin/vis_augmenter/associate_detector_spec.js
  cypress/integration/plugins/anomaly-detection-dashboards-plugin/vis_augmenter/augment_vis_saved_object_spec.js
  cypress/integration/plugins/anomaly-detection-dashboards-plugin/vis_augmenter/view_anomaly_events_spec.js
  cypress/utils/dashboards/vis-augmenter/commands.js
  cypress/utils/dashboards/vis-augmenter/helpers.js
  cypress/utils/plugins/anomaly-detection-dashboards-plugin/helpers.js
Labels: v2.9.0

#731 [Table Visualizations] Update test
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/table.spec.js
Labels: backport 2.x, v2.9.0

#739 [Vis Augmenter / Feature Anywhere] Add tests in core OSD and AD plugin
  cypress/fixtures/dashboard/opensearch_dashboards/vis-augmenter/sample-data-simple/data.json
  cypress/fixtures/dashboard/opensearch_dashboards/vis-augmenter/sample-data-simple/index-pattern-fields.txt
  cypress/fixtures/dashboard/opensearch_dashboards/vis-augmenter/sample-data-simple/index-settings.txt
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis-augmenter/dashboard_spec.js
  cypress/integration/plugins/anomaly-detection-dashboards-plugin/sample_detector_spec.js
  cypress/integration/plugins/anomaly-detection-dashboards-plugin/vis_augmenter/associate_detector_spec.js
  cypress/integration/plugins/anomaly-detection-dashboards-plugin/vis_augmenter/augment_vis_saved_object_spec.js
  cypress/integration/plugins/anomaly-detection-dashboards-plugin/vis_augmenter/view_anomaly_events_spec.js
  cypress/utils/dashboards/commands.js
  cypress/utils/dashboards/constants.js
  cypress/utils/dashboards/vis-augmenter/commands.js
  cypress/utils/dashboards/vis-augmenter/constants.js
  cypress/utils/dashboards/vis-augmenter/helpers.js
  cypress/utils/dashboards/vis-augmenter/index.d.ts
  cypress/utils/helpers.js
  cypress/utils/plugins/anomaly-detection-dashboards-plugin/helpers.js
Labels: backport 2.x, v2.9.0, backport 2.9

#748 Revert "[Vis Augmenter / Feature Anywhere] Add tests in core OSD and AD plugin"
  cypress/fixtures/dashboard/opensearch_dashboards/vis-augmenter/sample-data-simple/data.json
  cypress/fixtures/dashboard/opensearch_dashboards/vis-augmenter/sample-data-simple/index-pattern-fields.txt
  cypress/fixtures/dashboard/opensearch_dashboards/vis-augmenter/sample-data-simple/index-settings.txt
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis-augmenter/dashboard_spec.js
  cypress/integration/plugins/anomaly-detection-dashboards-plugin/sample_detector_spec.js
  cypress/integration/plugins/anomaly-detection-dashboards-plugin/vis_augmenter/associate_detector_spec.js
  cypress/integration/plugins/anomaly-detection-dashboards-plugin/vis_augmenter/augment_vis_saved_object_spec.js
  cypress/integration/plugins/anomaly-detection-dashboards-plugin/vis_augmenter/view_anomaly_events_spec.js
  cypress/utils/dashboards/commands.js
  cypress/utils/dashboards/constants.js
  cypress/utils/dashboards/vis-augmenter/commands.js
  cypress/utils/dashboards/vis-augmenter/constants.js
  cypress/utils/dashboards/vis-augmenter/helpers.js
  cypress/utils/dashboards/vis-augmenter/index.d.ts
  cypress/utils/helpers.js
  cypress/utils/plugins/anomaly-detection-dashboards-plugin/helpers.js
Labels: backport 2.x, v2.9.0, backport 2.9

#756 Test sample data with multiple data source enabled on local cluster
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/dashboard_sample_data_with_datasource_spec.js
Labels: backport 2.x, backport 2.9

#752 [Vis Augmenter] Add tests in OSD & AD plugin
  cypress/fixtures/dashboard/opensearch_dashboards/vis-augmenter/sample-data-simple/data.json
  cypress/fixtures/dashboard/opensearch_dashboards/vis-augmenter/sample-data-simple/index-pattern-fields.txt
  cypress/fixtures/dashboard/opensearch_dashboards/vis-augmenter/sample-data-simple/index-settings.txt
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis-augmenter/dashboard_spec.js
  cypress/integration/plugins/anomaly-detection-dashboards-plugin/sample_detector_spec.js
  cypress/integration/plugins/anomaly-detection-dashboards-plugin/vis_augmenter/associate_detector_spec.js
  cypress/integration/plugins/anomaly-detection-dashboards-plugin/vis_augmenter/augment_vis_saved_object_spec.js
  cypress/integration/plugins/anomaly-detection-dashboards-plugin/vis_augmenter/view_anomaly_events_spec.js
  cypress/utils/dashboards/commands.js
  cypress/utils/dashboards/constants.js
  cypress/utils/dashboards/vis-augmenter/commands.js
  cypress/utils/dashboards/vis-augmenter/constants.js
  cypress/utils/dashboards/vis-augmenter/helpers.js
  cypress/utils/dashboards/vis-augmenter/index.d.ts
  cypress/utils/helpers.js
  cypress/utils/plugins/anomaly-detection-dashboards-plugin/helpers.js
Labels: backport 2.x, v2.9.0, backport 2.9

#763 fix: Bump tough-cookie and word-wrap versions
  package-lock.json
  package.json
Labels: backport 2.x, security vulnerability, v2.9.0, backport 2.9

#772 feat: use "overrides" to install desired version of tough-cookie and word-wrap.
  DEVELOPER_GUIDE.md
  package-lock.json
  package.json
Labels: bug, dependencies, backport 2.x, backport 2.9

#778 Improve date selection across versions of OUI
  cypress/utils/commands.js
  cypress/utils/dashboards/commands.js
  cypress/utils/index.d.ts
Labels: backport 2.x, backport 2.7, backport 2.8, backport 2.9

#776 feat: sync cypress test from notifications-dashboards
  cypress/fixtures/plugins/notifications-dashboards/test_chime_channel.json
  cypress/fixtures/plugins/notifications-dashboards/test_email_recipient_group.json
  cypress/fixtures/plugins/notifications-dashboards/test_ses_sender.json
  cypress/fixtures/plugins/notifications-dashboards/test_slack_channel.json
  cypress/fixtures/plugins/notifications-dashboards/test_smtp_email_channel.json
  cypress/fixtures/plugins/notifications-dashboards/test_sns_channel.json
  cypress/fixtures/plugins/notifications-dashboards/test_ssl_smtp_sender.json
  cypress/fixtures/plugins/notifications-dashboards/test_tls_smtp_sender.json
  cypress/fixtures/plugins/notifications-dashboards/test_webhook_channel.json
  cypress/integration/plugins/notifications-dashboards/1_email_senders_and_groups.spec.js
  cypress/integration/plugins/notifications-dashboards/2_channels.spec.js
  cypress/support/index.js
  cypress/utils/plugins/notifications-dashboards/commands.js
  cypress/utils/plugins/notifications-dashboards/constants.js
Labels: backport 2.x, backport main

#785 [Table Visualizations] Tests cleanup
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/table.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_table/split.spec.js
Labels: backport 2.x, v2.10.0

#787 [Table Visualizations] Test Update
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/table.spec.js
Labels: backport 2.x, v2.10.0
