Repository opensearch-project/opensearch-dashboards-functional-test, pull requests merged in 2023-02, with the labels that each got.

#454 Clean up linter issues
  cypress/integration/plugins/security-analytics-dashboards-plugin/rules_spec.js
  cypress/support/index.js
  cypress/utils/constants.js
  cypress/utils/plugins/index-management-dashboards-plugin/commands.js
  cypress/utils/plugins/security-analytics-dashboards-plugin/commands.js
  site/js/dashboard.js
Labels: backport 2.5

#475 Fix Observability mapping url
  cypress/utils/plugins/observability-dashboards/constants.js
Labels: backport 1.x, backport 1.3, backport 2.x, backport 2.0, backport 2.2, backport 2.3, backport 2.1, backport 2.4, backport 2.5

#487 Fix flaky test in maps
  cypress/integration/plugins/custom-import-map-dashboards/documentsLayer.spec.js
Labels: backport 2.x, backport 2.5

#455 Update reports test
  cypress/integration/plugins/reports-dashboards/01-create.spec.js
  cypress/integration/plugins/reports-dashboards/02-edit.spec.js
  cypress/integration/plugins/reports-dashboards/04-download.spec.js
  cypress/utils/plugins/reports-dashboards/constants.js
Labels: backport 1.x, backport 1.3, backport 2.x, backport 2.3, backport 2.5

#508 Update dashboards observability tests
  cypress/integration/plugins/observability-dashboards/3_trace_analytics_traces.spec.js
  cypress/integration/plugins/observability-dashboards/5_event_analytics.spec.js
  cypress/integration/plugins/observability-dashboards/6_notebooks.spec.js
  cypress/integration/plugins/observability-dashboards/7_app_analytics.spec.js
Labels: backport 2.x, backport 2.4, backport 2.5

#515 Replacing day.js with moment.js -> 1.3 and older
  cypress/integration/plugins/gantt-chart-dashboards/gantt_ui.spec.js
Labels: backport 1.x

#516 [Backport 2.3] Update observability tests for versions prior to 2.4
  cypress/integration/plugins/observability-dashboards/0_before.spec.js
  cypress/integration/plugins/observability-dashboards/1_trace_analytics_dashboard.spec.js
  cypress/integration/plugins/observability-dashboards/3_trace_analytics_traces.spec.js
  cypress/integration/plugins/observability-dashboards/4_panels.spec.js
  cypress/integration/plugins/observability-dashboards/5_event_analytics.spec.js
  cypress/integration/plugins/observability-dashboards/6_notebooks.spec.js
  cypress/integration/plugins/observability-dashboards/7_app_analytics.spec.js
Labels: backport 1.x, backport 1.3, backport 2.0, backport 2.2, backport 2.1

#520 [Backport 1.3] Update observability tests for 1.3/1.x
  cypress/integration/plugins/observability-dashboards/7_app_analytics.spec.js
Labels: backport 1.x

#486 Added additional cypress tests for Security Analytics Dashboards plugin.
  .github/workflows/security-analytics-release-e2e-workflow.yml
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/integration_tests/detector/create_dns_detector_data.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/integration_tests/detector/create_dns_detector_mappings_data.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/integration_tests/detector/create_usb_detector_data.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/integration_tests/detector/create_usb_detector_mappings_data.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/integration_tests/index/add_dns_index_data.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/integration_tests/index/add_windows_index_data.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/integration_tests/index/create_dns_settings.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/integration_tests/index/create_windows_settings.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/integration_tests/rule/create_dns_rule.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/integration_tests/rule/create_windows_usb_rule.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/sample_alias_mappings.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/sample_detector.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/sample_document.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/sample_field_mappings.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/sample_index_settings.json
  cypress/integration/plugins/security-analytics-dashboards-plugin/1_detectors.spec.js
  cypress/integration/plugins/security-analytics-dashboards-plugin/2_rules.spec.js
  cypress/integration/plugins/security-analytics-dashboards-plugin/3_alerts.spec.js
  cypress/integration/plugins/security-analytics-dashboards-plugin/4_findings.spec.js
  cypress/integration/plugins/security-analytics-dashboards-plugin/5_integrations.spec.js
  cypress/integration/plugins/security-analytics-dashboards-plugin/rules_spec.js
  cypress/support/index.js
  cypress/utils/commands.js
  cypress/utils/constants.js
  cypress/utils/plugins/alerting-dashboards-plugin/commands.js
  cypress/utils/plugins/index-management-dashboards-plugin/commands.js
  cypress/utils/plugins/security-analytics-dashboards-plugin/commands.js
  cypress/utils/plugins/security-analytics-dashboards-plugin/constants.js
  site/js/dashboard.js
Labels: backport 2.x

#521 Fix workbench find full window button
  cypress/integration/plugins/query-workbench-dashboards/ui.spec.js
Labels: backport 2.x, backport 2.3, backport 2.4, backport 2.5

#443 feat: add function test for IM plugin
  .github/workflows/release-e2e-workflow-template.yml
  cypress/integration/plugins/index-management-dashboards-plugin/aliases.js
  cypress/integration/plugins/index-management-dashboards-plugin/create_index.js
  cypress/integration/plugins/index-management-dashboards-plugin/indices_spec.js
  cypress/integration/plugins/index-management-dashboards-plugin/reindex_spec.js
  cypress/integration/plugins/index-management-dashboards-plugin/split_index.js
  cypress/integration/plugins/index-management-dashboards-plugin/templates.js
  cypress/utils/plugins/index-management-dashboards-plugin/commands.js
Labels: backport 2.x, backport 2.5

#530 Update notebook and app analytics tests
  cypress/integration/plugins/observability-dashboards/6_notebooks.spec.js
  cypress/integration/plugins/observability-dashboards/7_app_analytics.spec.js
Labels: backport 2.x, backport 2.4, backport 2.5

#547 Fix Sql timeout
  cypress/integration/plugins/query-workbench-dashboards/ui.spec.js
Labels: backport 1.x, backport 1.3, backport 2.x, backport 2.0, backport 2.2, backport 2.3, backport 2.1, backport 2.4, backport 2.5

#554 Clean up flaky resource deletion for AD tests
  cypress/integration/plugins/anomaly-detection-dashboards-plugin/create_detector_spec.js
  cypress/integration/plugins/anomaly-detection-dashboards-plugin/detector_configuration_spec.js
  cypress/integration/plugins/anomaly-detection-dashboards-plugin/historical_analysis_spec.js
  cypress/integration/plugins/anomaly-detection-dashboards-plugin/sample_detector_spec.js
  cypress/utils/commands.js
Labels: backport 2.x, backport 2.5

#555 fix missed test case for dates
  cypress/integration/plugins/observability-dashboards/3_trace_analytics_traces.spec.js
Labels: backport 2.0, backport 2.2, backport 2.1

#538 Add functional test for ml-commons-dashboards overview page
  .github/workflows/ml-commons-release-e2e-workflow.yml
  cypress/integration/plugins/ml-commons-dashboards/overview_spec.js
  cypress/support/index.js
  cypress/utils/constants.js
  cypress/utils/plugins/ml-commons-dashboards/commands.js
  cypress/utils/plugins/ml-commons-dashboards/constants.js
  test_finder.sh
Labels: backport 2.x

#563 Disable only_run_on_ml_node to avoid model upload error
  cypress/integration/plugins/ml-commons-dashboards/overview_spec.js
  cypress/utils/plugins/ml-commons-dashboards/commands.js
Labels: backport 2.x

#561 Fix the flaky test case for security permission
  cypress/integration/plugins/security/permissions_spec.js
Labels: backport 2.x, v2.6.0

#474 [BUG]fix unknown setting [plugins.security.disabled] issue
  .github/workflows/release-e2e-workflow-template-windows.yml
  .github/workflows/release-e2e-workflow-template.yml
Labels: bug, backport 2.x

#567 Add experimental flag for ml commons dashboards
  .github/workflows/cypress-workflow-bundle-snapshot-based.yml
  .github/workflows/ml-commons-release-e2e-workflow.yml
  cypress.json
  cypress/integration/plugins/ml-commons-dashboards/overview_spec.js
Labels: backport 2.x, backport 2.6

#571 Disable native memory circuit breaker before model upload
  cypress/integration/plugins/ml-commons-dashboards/overview_spec.js
  cypress/utils/plugins/ml-commons-dashboards/commands.js
Labels: backport 2.x, backport 2.6

#570 Fix: failed test spec on 2.6
  cypress/integration/plugins/index-management-dashboards-plugin/aliases.js
  cypress/integration/plugins/index-management-dashboards-plugin/managed_indices_spec.js
  cypress/integration/plugins/index-management-dashboards-plugin/policies_spec.js
Labels: backport 2.x, backport 2.6

#579 Maps: remove indices after run
  cypress/integration/plugins/custom-import-map-dashboards/documentsLayer.spec.js
  cypress/integration/plugins/custom-import-map-dashboards/opensearchMapLayer.spec.js
Labels: backport 2.x, backport 2.6
