Repository opensearch-project/opensearch-dashboards-functional-test, pull requests merged in 2023-09, with the labels that each got.

#813 feat: add test cases for remote models
  cypress/integration/plugins/ml-commons-dashboards/overview_spec.js
  cypress/utils/plugins/ml-commons-dashboards/commands.js
  cypress/utils/plugins/ml-commons-dashboards/constants.js
Labels: backport 2.x

#814 fix workbench download text and csv schema
  cypress/integration/plugins/query-workbench-dashboards/ui.spec.js
Labels: backport 2.x, backport main

#775 update trace analytics cypress tests according to observability changes
  cypress/integration/plugins/observability-dashboards/1_trace_analytics_dashboard.spec.js
Labels: backport 2.x, v2.10.0

#823 [Dashboard] Retry visbuilder dashboard test
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/dashboard.spec.js
Labels: backport 2.x, v2.10.0

#832 Add new tests for alerting dashboards
  cypress/fixtures/plugins/alerting-dashboards-plugin/sample_cluster_metrics_health_monitor.json
  cypress/fixtures/plugins/alerting-dashboards-plugin/sample_cluster_metrics_stats_monitor.json
  cypress/fixtures/plugins/alerting-dashboards-plugin/sample_composite_level_monitor.json
  cypress/integration/plugins/alerting-dashboards-plugin/cluster_metrics_monitor_spec.js
  cypress/integration/plugins/alerting-dashboards-plugin/composite_level_monitor_spec.js
  cypress/integration/plugins/alerting-dashboards-plugin/monitors_dashboard_spec.js
  cypress/integration/plugins/alerting-dashboards-plugin/query_level_monitor_spec.js
  cypress/utils/plugins/alerting-dashboards-plugin/commands.js
  cypress/utils/plugins/alerting-dashboards-plugin/constants.js
Labels: backport 2.x, v2.10.0, backport 2.10

#835 Updated cypress commands to avoid duplication
  cypress/integration/plugins/security-analytics-dashboards-plugin/1_detectors.spec.js
  cypress/utils/plugins/security-analytics-dashboards-plugin/commands.js
  cypress/utils/plugins/security-analytics-dashboards-plugin/constants.js
  cypress/utils/plugins/security-analytics-dashboards-plugin/index.d.ts
Labels: v2.10.0, backport 2.10

#844 Update source element in import_vector_map_tab.spec.js
  cypress/integration/plugins/custom-import-map-dashboards/import_vector_map_tab.spec.js
Labels: backport 2.x, backport 2.10

#857 Buffer `waitForLoader` before checking for icon
  cypress.json
  cypress/utils/dashboards/commands.js
  package.json
Labels: backport 2.x, backport main, v2.10.0

#867 Bump WAIT_FOR_LOADER_BUFFER to 3000 ms
  package.json
Labels: backport 2.x, backport main, v2.10.0

#869 [Vis builder] get correct element
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/dashboard.spec.js
Labels: backport 2.x, backport main, v2.10.0, backport 2.10

#872 [Alerting 2.10] Use input element for typing when selecting delegate monitor
  cypress/integration/plugins/alerting-dashboards-plugin/composite_level_monitor_spec.js
Labels: v2.10.0

#873 [Index-mgmt 2.10] Renamed index to avoid collision for other tests
  cypress/integration/plugins/index-management-dashboards-plugin/indices_spec.js
Labels: v2.10.0

#876 Fix reporting by removing flaky test and using data-test-subj instead of counting
  cypress/integration/plugins/reports-dashboards/04-download.spec.js
Labels: v2.10.0

#875 [Vis Builder] disable vis builder tests for with security
  package.json
Labels: v2.10.0

#877 [Alerting 2.10] Wait before checking update status for composite monitor
  cypress/integration/plugins/alerting-dashboards-plugin/composite_level_monitor_spec.js
Labels: v2.10.0

#884 Ignore the flaky test of opensearchMapLayer when security enabled
  cypress/integration/plugins/custom-import-map-dashboards/opensearchMapLayer.spec.js
Labels: backport 2.x, v2.10.0

#888 Skip failing test for reporting
  cypress/integration/plugins/reports-dashboards/04-download.spec.js
Labels: v2.10.0

#893 [2.10] core skip with filter for embed spec on security
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_table/embed.spec.js
Labels: backport 2.x, v2.10.0

#899 [2.10] Bump patch version
  package.json
Labels: v2.10.1
