Repository opensearch-project/opensearch-dashboards-functional-test, pull requests merged in 2023-04, with the labels that each got.

#606 Update MAINTAINERS.md and CODEOWNERS
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: backport 2.x

#604 add test case for model deployment details loading indicator
  cypress/integration/plugins/ml-commons-dashboards/overview_spec.js
  cypress/utils/plugins/ml-commons-dashboards/constants.js
Labels: backport 2.x, v2.7.0

#616 Chore: updates datepicker command for change in oui 1.1
  cypress/utils/dashboards/commands.js
Labels: backport 2.x, v2.7.0, backport 2.7

#619 updates package lock for new library changes
  package-lock.json
Labels: backport 2.x, v2.7.0, backport 2.7

#607 Add ISM cypress test for 2.7
  cypress/integration/plugins/index-management-dashboards-plugin/create_index.js
  cypress/integration/plugins/index-management-dashboards-plugin/data_streams.js
  cypress/integration/plugins/index-management-dashboards-plugin/force_merge.js
  cypress/integration/plugins/index-management-dashboards-plugin/rollover.js
  cypress/integration/plugins/index-management-dashboards-plugin/template_components.js
  cypress/integration/plugins/index-management-dashboards-plugin/templates.js
  cypress/utils/commands.js
  cypress/utils/plugins/index-management-dashboards-plugin/commands.js
  cypress/utils/plugins/index-management-dashboards-plugin/constants.js
Labels: roadmap, backport 2.x, v2.7.0, release, backport 2.7

#623 Update url for observability event and app analytics
  cypress/utils/plugins/observability-dashboards/constants.js
Labels: backport 2.x, backport 2.7

#552 Add Cypress test for Default Saved Map
  cypress/integration/plugins/custom-import-map-dashboards/add_saved_object.spec.js
Labels: backport 2.x, backport 2.6, backport 2.7

#622 Added additional security analytics and updated alerting cypress tests for 2.7 release.
  .github/workflows/security-analytics-release-e2e-workflow.yml
  cypress/fixtures/plugins/alerting-dashboards-plugin/sample_alerts_flyout_bucket_level_monitor.json
  cypress/fixtures/plugins/alerting-dashboards-plugin/sample_alerts_flyout_query_level_monitor.json
  cypress/fixtures/plugins/alerting-dashboards-plugin/sample_cluster_metrics_monitor.json
  cypress/fixtures/plugins/alerting-dashboards-plugin/sample_document_level_monitor.json
  cypress/fixtures/plugins/alerting-dashboards-plugin/sample_visual_editor_bucket_level_monitor.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/integration_tests/detector/create_dns_detector_data.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/integration_tests/detector/create_dns_detector_mappings_data.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/integration_tests/detector/create_usb_detector_data.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/integration_tests/detector/create_usb_detector_mappings_data.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/integration_tests/index/add_dns_index_data.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/integration_tests/index/add_windows_index_data.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/integration_tests/index/create_dns_settings.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/integration_tests/index/create_windows_settings.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/integration_tests/rule/create_dns_rule.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/integration_tests/rule/create_network_rule.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/integration_tests/rule/create_windows_usb_rule.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/sample_alias_mappings.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/sample_detector.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/sample_document.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/sample_field_mappings.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/sample_index_settings.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/sample_network_index_settings.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/sample_rule.json
  cypress/integration/plugins/alerting-dashboards-plugin/alerts_dashboard_flyout_spec.js
  cypress/integration/plugins/alerting-dashboards-plugin/bucket_level_monitor_spec.js
  cypress/integration/plugins/alerting-dashboards-plugin/document_level_monitor_spec.js
  cypress/integration/plugins/alerting-dashboards-plugin/query_level_monitor_spec.js
  cypress/integration/plugins/notifications-dashboards/2_channels.spec.js
  cypress/integration/plugins/security-analytics-dashboards-plugin/1_detectors.spec.js
  cypress/integration/plugins/security-analytics-dashboards-plugin/2_rules.spec.js
  cypress/integration/plugins/security-analytics-dashboards-plugin/3_alerts.spec.js
  cypress/integration/plugins/security-analytics-dashboards-plugin/4_findings.spec.js
  cypress/support/index.js
  cypress/utils/commands.js
  cypress/utils/constants.js
  cypress/utils/plugins/alerting-dashboards-plugin/commands.js
  cypress/utils/plugins/security-analytics-dashboards-plugin/commands.js
  cypress/utils/plugins/security-analytics-dashboards-plugin/constants.js
  cypress/utils/plugins/security-analytics-dashboards-plugin/detectors.js
  cypress/utils/plugins/security-analytics-dashboards-plugin/rules.js
  cypress/utils/plugins/security-analytics-dashboards-plugin/typings.js
  package-lock.json
  package.json
  site/js/dashboard.js
  test_finder.sh
Labels: backport 2.x, backport 2.7

#627 Update notebooks test for 2.7
  cypress/integration/plugins/observability-dashboards/6_notebooks.spec.js
Labels: backport 2.x, backport 2.7

#631 Update traces tests for 2.7
  cypress/integration/plugins/observability-dashboards/1_trace_analytics_dashboard.spec.js
  cypress/integration/plugins/observability-dashboards/2_trace_analytics_services.spec.js
  cypress/integration/plugins/observability-dashboards/3_trace_analytics_traces.spec.js
Labels: backport 2.x, v2.7.0, backport 2.7

#639 [Backport 2.x] Added additional security analytics and updated alerting cypress tests for 2.7 release.
  cypress/fixtures/plugins/alerting-dashboards-plugin/sample_alerts_flyout_bucket_level_monitor.json
  cypress/fixtures/plugins/alerting-dashboards-plugin/sample_alerts_flyout_query_level_monitor.json
  cypress/fixtures/plugins/alerting-dashboards-plugin/sample_cluster_metrics_monitor.json
  cypress/fixtures/plugins/alerting-dashboards-plugin/sample_document_level_monitor.json
  cypress/fixtures/plugins/alerting-dashboards-plugin/sample_visual_editor_bucket_level_monitor.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/integration_tests/detector/create_dns_detector_data.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/integration_tests/detector/create_dns_detector_mappings_data.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/integration_tests/detector/create_usb_detector_data.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/integration_tests/detector/create_usb_detector_mappings_data.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/integration_tests/index/add_dns_index_data.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/integration_tests/index/add_windows_index_data.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/integration_tests/index/create_dns_settings.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/integration_tests/index/create_windows_settings.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/integration_tests/rule/create_dns_rule.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/integration_tests/rule/create_network_rule.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/integration_tests/rule/create_windows_usb_rule.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/sample_alias_mappings.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/sample_detector.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/sample_document.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/sample_field_mappings.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/sample_index_settings.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/sample_network_index_settings.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/sample_rule.json
  cypress/integration/plugins/alerting-dashboards-plugin/alerts_dashboard_flyout_spec.js
  cypress/integration/plugins/alerting-dashboards-plugin/bucket_level_monitor_spec.js
  cypress/integration/plugins/alerting-dashboards-plugin/document_level_monitor_spec.js
  cypress/integration/plugins/alerting-dashboards-plugin/query_level_monitor_spec.js
  cypress/integration/plugins/notifications-dashboards/1_email_senders_and_groups.spec.js
  cypress/integration/plugins/notifications-dashboards/2_channels.spec.js
  cypress/integration/plugins/security-analytics-dashboards-plugin/1_detectors.spec.js
  cypress/integration/plugins/security-analytics-dashboards-plugin/2_rules.spec.js
  cypress/integration/plugins/security-analytics-dashboards-plugin/3_alerts.spec.js
  cypress/integration/plugins/security-analytics-dashboards-plugin/4_findings.spec.js
  cypress/integration/plugins/security-analytics-dashboards-plugin/rules_spec.js
  cypress/support/index.js
  cypress/utils/commands.js
  cypress/utils/plugins/alerting-dashboards-plugin/commands.js
  cypress/utils/plugins/security-analytics-dashboards-plugin/commands.js
  cypress/utils/plugins/security-analytics-dashboards-plugin/constants.js
  cypress/utils/plugins/security-analytics-dashboards-plugin/detectors.js
  cypress/utils/plugins/security-analytics-dashboards-plugin/rules.js
  cypress/utils/plugins/security-analytics-dashboards-plugin/typings.js
  package-lock.json
  package.json
  site/js/dashboard.js
  test_finder.sh
Labels: backport 2.7

#641 Update Observability panel and trace tests
  cypress/integration/plugins/observability-dashboards/1_trace_analytics_dashboard.spec.js
  cypress/integration/plugins/observability-dashboards/2_trace_analytics_services.spec.js
  cypress/integration/plugins/observability-dashboards/3_trace_analytics_traces.spec.js
  cypress/integration/plugins/observability-dashboards/4_panels.spec.js
  cypress/utils/plugins/observability-dashboards/constants.js
Labels: backport 2.x, v2.7.0, backport 2.7

#644 Add an optional parameter -o to integtest.sh
  integtest.sh
  test_finder.sh
Labels: backport 2.x, backport 2.7
