Repository opensearch-project/opensearch-dashboards-functional-test, pull requests merged in 2023-05, with the labels that each got.

#647 Fix Failing Test in custom-import-map-dashboards
  cypress/integration/plugins/custom-import-map-dashboards/add_saved_object.spec.js
Labels: backport 2.x

#658 Bump version to 2.7.1
  package.json
Labels: v2.7.1

#663 Change the testuser password into a strong password in aggregation_view test
  cypress/fixtures/plugins/security-dashboards-plugin/users/testUser.json
  cypress/integration/plugins/security-dashboards-plugin/aggregation_view.js
Labels: backport 2.x

#423 [Table visualization] Add functional tests for new table vis
  cypress/fixtures/dashboard/opensearch_dashboards/vis_type_table/table.data.txt
  cypress/fixtures/dashboard/opensearch_dashboards/vis_type_table/table_saved_objects.ndjson
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_table/basic.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_table/data.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_table/embed.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_table/options.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_table/split.spec.js
  cypress/utils/dashboards/commands.js
  cypress/utils/dashboards/constants.js
  cypress/utils/dashboards/vis_type_table/buckets_agg.js
  cypress/utils/dashboards/vis_type_table/commands.js
  cypress/utils/dashboards/vis_type_table/constants.js
  cypress/utils/dashboards/vis_type_table/data_panel.js
  cypress/utils/dashboards/vis_type_table/index.d.ts
  cypress/utils/dashboards/vis_type_table/inspector.js
  cypress/utils/dashboards/vis_type_table/options_panel.js
  cypress/utils/dashboards/vis_type_table/table.js
Labels: backport 2.x, backport 2.7

#670 [2.x] Remove duplicate securityAnalyticsDashboards
  test_finder.sh
Labels: bug, v2.8.0, release, backport 2.7

#674 Make ml commons dashboards true by default
  cypress.json
Labels: backport 2.x, v2.8.0, release

#678 Allow ftrepo to accept custom browser path running integTest
  integtest.sh
Labels: enhancement, backport 1.x, backport 1.3, backport 2.x, windows, v2.8.0, release

#677 fix: model upload failed with model group level access control
  cypress/integration/plugins/ml-commons-dashboards/overview_spec.js
  cypress/utils/plugins/ml-commons-dashboards/commands.js
  cypress/utils/plugins/ml-commons-dashboards/constants.js
Labels: bug, backport 2.x

#676 Update vanilla snapshot test to 2.7.0 and replace deprecated set-output
  .github/workflows/cypress-workflow-plugins-bundle-snapshot-based.yml.disabled
  .github/workflows/cypress-workflow-vanilla-snapshot-based.yml
  .github/workflows/cypress-workflow-vanilla-source-based.yml.disabled
  .github/workflows/release-e2e-workflow-template.yml
  .github/workflows/release-signoff-chrome.yml
  .github/workflows/release-signoff-chromium-ad-only.yml
  .github/workflows/release-signoff-chromium-ism-only.yml
  .github/workflows/release-signoff-chromium-tests-in-memory-0.yml
  .github/workflows/release-signoff-chromium-tests-in-memory-10.yml
  .github/workflows/release-signoff-chromium-tests-in-memory-20.yml
  .github/workflows/release-signoff-chromium-tests-in-memory-5.yml
  .github/workflows/release-signoff-chromium.yml
  .github/workflows/release-signoff-electron.yml
  .github/workflows/release-signoff-firefox.yml
Labels: bug, enhancement, backport 1.x, backport 1.3, backport 2.x, v2.8.0, release

#669 [MD]Update cypress tests for sigV4 & serverless support
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/datasource-management-plugin/1_create_datasource.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/datasource-management-plugin/2_datasource_table.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/datasource-management-plugin/3_update_datasource.spec.js
  cypress/utils/dashboards/datasource-management-dashboards-plugin/constants.js
Labels: backport 2.x

#688 Tweak dir path for osd after untar
  .github/workflows/release-e2e-workflow-template.yml
  .github/workflows/release-signoff-chrome.yml
  .github/workflows/release-signoff-chromium-ad-only.yml
  .github/workflows/release-signoff-chromium-ism-only.yml
  .github/workflows/release-signoff-chromium-tests-in-memory-0.yml
  .github/workflows/release-signoff-chromium-tests-in-memory-10.yml
  .github/workflows/release-signoff-chromium-tests-in-memory-20.yml
  .github/workflows/release-signoff-chromium-tests-in-memory-5.yml
  .github/workflows/release-signoff-chromium.yml
  .github/workflows/release-signoff-electron.yml
  .github/workflows/release-signoff-firefox.yml
Labels: bug, backport 1.3, backport 2.x

#682 Update table vis test in dashboard_filtering_spec.js
  cypress/fixtures/dashboard/opensearch_dashboards/data.json.txt
  cypress/integration/core-opensearch-dashboards/vanilla-opensearch-dashboards/dashboard_filtering_spec.js
Labels: backport 2.x

#693 Add cypress test of index management dashboards plugin on 2.8
  cypress/integration/plugins/index-management-dashboards-plugin/aliases.js
  cypress/integration/plugins/index-management-dashboards-plugin/data_streams.js
  cypress/integration/plugins/index-management-dashboards-plugin/force_merge.js
  cypress/integration/plugins/index-management-dashboards-plugin/indices_spec.js
  cypress/integration/plugins/index-management-dashboards-plugin/notification_settings.js
  cypress/integration/plugins/index-management-dashboards-plugin/refresh_index.js
  cypress/integration/plugins/index-management-dashboards-plugin/template_components.js
Labels: backport 2.x, backport 2.8

#694 Enhancement ml-commons model upload compatible with register model group failed
  cypress/integration/plugins/ml-commons-dashboards/overview_spec.js
  cypress/utils/plugins/ml-commons-dashboards/commands.js
Labels: backport 2.x, backport 2.8

#692 Update create table url and address style render
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_table/data.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_table/split.spec.js
  cypress/utils/dashboards/vis_type_table/constants.js
  cypress/utils/dashboards/vis_type_table/table.js
Labels: backport 2.x, backport 2.8

#702 Use range for filter
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_table/data.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_table/embed.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_table/options.spec.js
  package-lock.json
Labels: backport 2.x, backport 2.8
