Repository opensearch-project/opensearch-dashboards-functional-test, pull requests merged in 2023-11, with the labels that each got.

#949 Fix observability event analytics and notebook failing tests
  cypress/integration/plugins/observability-dashboards/5_event_analytics.spec.js
  cypress/integration/plugins/observability-dashboards/6_notebooks.spec.js
Labels: backport 2.x, backport main

#953 Refactored alerting test, and added wait logic to reduce flakiness.
  cypress/integration/plugins/alerting-dashboards-plugin/monitors_dashboard_spec.js
Labels: backport 2.x, backport 2.10, backport 2.11

#960 feat: use ipv4 by default to fix CI flow
  .github/workflows/cypress-workflow-vanilla-snapshot-based.yml
  .github/workflows/lint_checker.yml
  .github/workflows/release-e2e-workflow-template-windows.yml
  .github/workflows/release-e2e-workflow-template.yml
  .github/workflows/release-signoff-chrome.yml
  .github/workflows/release-signoff-chromium-ad-only.yml
  .github/workflows/release-signoff-chromium-ism-only.yml
  .github/workflows/release-signoff-chromium-tests-in-memory-0.yml
  .github/workflows/release-signoff-chromium-tests-in-memory-10.yml
  .github/workflows/release-signoff-chromium-tests-in-memory-20.yml
  .github/workflows/release-signoff-chromium-tests-in-memory-5.yml
  .github/workflows/release-signoff-chromium.yml
  .github/workflows/release-signoff-electron.yml
  .github/workflows/release-signoff-firefox.yml
Labels: backport 2.x

#940 Integration tests for broken safari link
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/dashboard_share_copy_link_test.js
Labels: backport 2.x
