Repository opensearch-project/opensearch-dashboards-functional-test, pull requests merged in 2024-07, with the labels that each got.

#1440 Add tests to Ci group
  package.json
Labels: backport 2.x, v2.16.0

#1442 Fix workspace failed integration tests
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_create.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_import_sample_data_to.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_overview.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_update.spec.js
  cypress/utils/dashboards/workspace-plugin/commands.js
Labels: backport 2.x, v2.16.0

#1447 [2.x] Fixes flaky-ness in permissions spec test
  cypress.json
  cypress/integration/plugins/security-dashboards-plugin/inaccessible_tenancy_features.js
  cypress/integration/plugins/security-dashboards-plugin/readonly.js
  cypress/integration/plugins/security-dashboards-plugin/switch_tenant.js
  cypress/integration/plugins/security/permissions_spec.js
Labels: backport 2.16

#1453 Fixed v2.15 alerting tests.
  cypress/integration/plugins/alerting-dashboards-plugin/cluster_metrics_monitor_spec.js
  cypress/integration/plugins/alerting-dashboards-plugin/composite_level_monitor_spec.js
Labels: backport 2.x, backport 2.14, backport 2.15, v2.16.0, backport 2.16

#1446 Remove workspace overview and update test cases
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_create.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_detail.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_dropdown_menu.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_overview.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_update.spec.js
Labels: backport 2.x, v2.16.0, backport 2.16
