Repository opensearch-project/opensearch-dashboards-functional-test, pull requests merged in 2024-03, with the labels that each got.

#789 Auto release the repo once a new tag is created as part of the release
  .github/workflows/auto-release.yml
Labels: backport 2.x, v2.11.0

#1121 bump version from 2.12 to 2.13
  package.json
Labels: v2.13.0

#1149 Update dashboards assistant trace button functional test
  cypress/fixtures/plugins/dashboards-assistant/security-cert.js
  cypress/integration/plugins/dashboards-assistant/chatbot_interaction_trace_spec.js
Labels: backport 2.x, v2.13.0

#1148 [Discover] toggle for legacy mode
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/date_nanos.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/date_nanos_mixed.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/field_data.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/index_pattern_with_encoded_id.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/index_pattern_without_field.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/saved_queries.spec.js
  cypress/utils/dashboards/data_explorer/commands.js
Labels: backport 2.x, v2.13.0

#1153 Revert "[Discover] toggle for legacy mode (#1148)"
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/date_nanos.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/date_nanos_mixed.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/field_data.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/index_pattern_with_encoded_id.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/index_pattern_without_field.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/saved_queries.spec.js
  cypress/utils/dashboards/data_explorer/commands.js
Labels: backport 2.x

#1155 [Discover] update tests related to legacy view
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/date_nanos.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/date_nanos_mixed.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/field_data.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/index_pattern_with_encoded_id.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/index_pattern_without_field.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/saved_queries.spec.js
  cypress/utils/dashboards/data_explorer/commands.js
Labels: backport 2.x, v2.13.0

#1147 [maps-dashboards] Update data source name and rebase code in maps
  cypress/integration/plugins/custom-import-map-dashboards/1_import_vector_map_tab.spec.js
  cypress/integration/plugins/custom-import-map-dashboards/2_opensearchMapLayer.spec.js
  cypress/integration/plugins/custom-import-map-dashboards/3_add_saved_object.spec.js
  cypress/integration/plugins/custom-import-map-dashboards/4_documentsLayer.spec.js
Labels: backport 2.x, v2.13.0

#1141 add functional test for sidecar
  cypress/integration/plugins/dashboards-assistant/chatbot_interaction_trace_spec.js
  cypress/integration/plugins/dashboards-assistant/chatbot_sidecar_spec.js
  cypress/integration/plugins/dashboards-assistant/conversation_history_spec.js
Labels: backport 2.x, v2.13.0, backport 2.13

#1140 include security-dashboards-plugin into security CI
  .github/workflows/security-release-e2e-workflow.yml
Labels: backport 2.x

#1171 [Security Analytics][2.13] Updates rules tests
  cypress/integration/plugins/security-analytics-dashboards-plugin/2_rules.spec.js
Labels: backport 2.x, backport main, v2.13.0

#1170 [Discover] set local storage directly for large string spec
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/large_string.spec.js
Labels: backport 2.x, v2.13.0, backport 2.13

#1177 [Alerting][2.13] Improve acknowledge alerts tests
  cypress/integration/plugins/alerting-dashboards-plugin/acknowledge_alerts_modal_spec.js
Labels: backport 2.x, backport main

#1174 Refactor 6_notebooks.spec.js
  cypress/integration/plugins/observability-dashboards/6_notebooks.spec.js
  cypress/utils/plugins/observability-dashboards/constants.js
Labels: backport 2.x, v2.13.0, backport 2.13

#1017 fix(workflow): paths-filter error on push event
  .github/workflows/cypress-workflow-bundle-snapshot-based-windows.yml
  .github/workflows/cypress-workflow-bundle-snapshot-based.yml
Labels: backport 2.x

#958 #3530 enhance sanity testing framework
  cypress/integration/plugins/security-dashboards-plugin/sanity_tests.spec.js
Labels: backport 2.x

#1189 [Backport 2.13] rollups/transform: wait for page to render
  cypress/integration/plugins/index-management-dashboards-plugin/rollups_spec.js
  cypress/integration/plugins/index-management-dashboards-plugin/transforms_spec.js
Labels: v2.13.0

#1091 rollups/transform: wait for page to render
  cypress/integration/plugins/index-management-dashboards-plugin/rollups_spec.js
  cypress/integration/plugins/index-management-dashboards-plugin/transforms_spec.js
Labels: backport 2.x

#1187 Fix Flaky Dashboards Visualization Tests
  cypress/integration/plugins/gantt-chart-dashboards/gantt_ui.spec.js
Labels: backport 2.x, v2.13.0, backport 2.13

#1195 [2.13] Switch to Private Tenant for Gantt Charts Tests
  cypress/integration/plugins/gantt-chart-dashboards/gantt_ui.spec.js
Labels: backport 2.x, backport main, v2.13.0
