Repository opensearch-project/opensearch-dashboards-functional-test, pull requests merged in 2024-11, with the labels that each got.

#1619 skip searchOnPageLoad test in 2.18
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover_advanced_settings.spec.js
Labels: v2.18.0

#1621 fix lint issue in 2.x
  cypress/integration/plugins/observability-dashboards/2_trace_analytics_services.spec.js
  cypress/utils/plugins/observability-dashboards/constants.js
Labels: backport 2.18

#1612 Update modal buttons for FF tests
  cypress/integration/plugins/dashboards-flow-framework/create_workflow_spec.js
Labels: backport 2.x

#1624 Fix duplicate test cypress result name
  .github/workflows/cypress-workflow-bundle-snapshot-based-ci-groups.yml
  .github/workflows/release-e2e-workflow-template.yml
Labels: backport 2.x

#1556 [Workspace]Fix workspace functional tests
  .github/workflows/ml-commons-release-e2e-workflow.yml
  .github/workflows/workspace-release-e2e-workflow.yml
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_create.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_detail.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_import_sample_data_to.spec.js
  cypress/support/index.js
  cypress/utils/commands.js
  cypress/utils/dashboards/datasource-management-dashboards-plugin/commands.js
  cypress/utils/dashboards/workspace-plugin/commands.js
  cypress/utils/plugins/ml-commons-dashboards/commands.js
Labels: backport main, v2.17.0, backport 2.17

#1634 Update flow framework visible plugin name
  cypress/utils/plugins/dashboards-flow-framework/constants.js
Labels: backport 2.x

#1633 Add cypress test for workspace overview page
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_analytics_overviews.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_essential_overviews.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_search_overviews.spec.js
  cypress/utils/commands.js
Labels: backport 2.x

#1598 Add cypress tests for discover 2.0
  cypress/fixtures/dashboard/opensearch_dashboards/query_enhancement/data.json.txt
  cypress/fixtures/dashboard/opensearch_dashboards/query_enhancement/data_with_index_pattern.json.txt
  cypress/fixtures/dashboard/opensearch_dashboards/query_enhancement/mappings.json.txt
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancement/dataset_navigator.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/query_enhancement/queries.spec.js
  cypress/utils/dashboards/commands.js
  cypress/utils/dashboards/constants.js
  cypress/utils/dashboards/query_enhancement/commands.js
  cypress/utils/dashboards/query_enhancement/constants.js
  package.json
Labels: backport 2.x, v2.19.0

#1636 Add workspace initial page functional tests
  cypress/fixtures/dashboard/opensearch_dashboards/workspace/workspaceTestRole.json
  cypress/fixtures/dashboard/opensearch_dashboards/workspace/workspaceTestRoleMapping.json
  cypress/fixtures/dashboard/opensearch_dashboards/workspace/workspaceTestUser.json
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_initial.spec.js
  cypress/utils/plugins/security-dashboards-plugin/commands.js
Labels: backport 2.x

#1618 modify the refresh data button test to use test-data-subj
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover_advanced_settings.spec.js
Labels: backport 2.x, v2.19.0

#1632 [Workspace] add tests for workspace collaborators page
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_collaborators.spec.js
Labels: backport 2.x

#1639 [workspace] Add integration test cases for workspace assets.
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_assets.spec.js
Labels: backport 2.x

#1644 [Workspace] Add ACL related test cases
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_acl.spec.js
Labels: backport 2.x

#1649 Add yubonluo as maintainer
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: backport 2.x

#1646 [Workspace] add tests for data source association and dissociation
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_association.spec.js
Labels: backport 2.x

#1635 Add test cases for workspace creation
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_create.spec.js
Labels: backport 2.x

#1630 Add different access level test cases in workspace update flow
  cypress/fixtures/dashboard/opensearch_dashboards/workspace/workspaceTestRole.json
  cypress/fixtures/dashboard/opensearch_dashboards/workspace/workspaceTestRoleMapping.json
  cypress/fixtures/dashboard/opensearch_dashboards/workspace/workspaceTestUser.json
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_detail.spec.js
Labels: backport 2.x

#1659 refactor: use function to make test cases reusable
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_acl.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_analytics_overviews.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_assets.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_association.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_breadcrumbs.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_collaborators.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_create.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_delete.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_detail.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_essential_overviews.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_import_sample_data_to.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_initial.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_search_overviews.spec.js
  cypress/utils/dashboards/workspace-plugin/test-cases/mds_workspace_acl.cases.js
  cypress/utils/dashboards/workspace-plugin/test-cases/mds_workspace_analytics_overviews.cases.js
  cypress/utils/dashboards/workspace-plugin/test-cases/mds_workspace_assets.cases.js
  cypress/utils/dashboards/workspace-plugin/test-cases/mds_workspace_association.cases.js
  cypress/utils/dashboards/workspace-plugin/test-cases/mds_workspace_breadcrumbs.cases.js
  cypress/utils/dashboards/workspace-plugin/test-cases/mds_workspace_collaborators.cases.js
  cypress/utils/dashboards/workspace-plugin/test-cases/mds_workspace_create.cases.js
  cypress/utils/dashboards/workspace-plugin/test-cases/mds_workspace_delete.cases.js
  cypress/utils/dashboards/workspace-plugin/test-cases/mds_workspace_detail.cases.js
  cypress/utils/dashboards/workspace-plugin/test-cases/mds_workspace_essential_overviews.cases.js
  cypress/utils/dashboards/workspace-plugin/test-cases/mds_workspace_import_sample_data_to.cases.js
  cypress/utils/dashboards/workspace-plugin/test-cases/mds_workspace_initial.cases.js
  cypress/utils/dashboards/workspace-plugin/test-cases/mds_workspace_search_overviews.cases.js
Labels: backport 2.x
