Repository opensearch-project/opensearch-dashboards-functional-test, pull requests merged in 2024-02, with the labels that each got.

#1030 ism-plugin: fix tests
  cypress/integration/plugins/index-management-dashboards-plugin/indices_spec.js
  cypress/integration/plugins/index-management-dashboards-plugin/managed_indices_spec.js
  cypress/integration/plugins/index-management-dashboards-plugin/notification_settings.js
  cypress/integration/plugins/index-management-dashboards-plugin/rollups_spec.js
Labels: backport 2.x

#1023 fixed observability tests running forever
  cypress/integration/plugins/observability-dashboards/1_trace_analytics_dashboard.spec.js
Labels: backport 2.x

#1029 add test cases for assistant feedback
  cypress/integration/plugins/dashboards-assistant/feedback_spec.js
Labels: backport 2.x

#1028 feat: add functional tests for conversation save to notebook
  cypress/integration/plugins/dashboards-assistant/conversation_save_to_notebook_spec.js
  cypress/utils/plugins/dashboards-assistant/helpers.js
Labels: backport 2.x

#1027 feat: add regenerate cases
  cypress/integration/plugins/dashboards-assistant/chatbot_agent_framework_spec.js
Labels: backport 2.x

#1006 Improve Observability Panels Tests
  cypress/integration/plugins/observability-dashboards/4_panels.spec.js
  cypress/utils/plugins/observability-dashboards/constants.js
Labels: backport 2.x

#1058 Improve bash checking in test_finder.sh for all OSes
  test_finder.sh
Labels: bug, backport 1.3, backport 2.x

#1053 Comply with the root agent id config change in dashboards-assistant
  .github/workflows/assistant-release-e2e-workflow.yml
  cypress/fixtures/plugins/dashboards-assistant/cluster_settings.json
  cypress/fixtures/plugins/dashboards-assistant/security-cert.js
  cypress/integration/plugins/dashboards-assistant/chatbot_agent_framework_spec.js
  cypress/support/index.js
  cypress/utils/plugins/dashboards-assistant/commands.js
  cypress/utils/plugins/dashboards-assistant/constants.js
Labels: backport main

#1057 Fix dashboards observability and reporting test CI issue
  cypress/integration/plugins/observability-dashboards/4_panels.spec.js
  cypress/integration/plugins/reports-dashboards/04-download.spec.js
Labels: backport main

#1065 Notebooks add index refresh, remove SQL check in paragraph
  cypress/integration/plugins/observability-dashboards/6_notebooks.spec.js
  cypress/utils/plugins/observability-dashboards/constants.js
Labels: backport main

#1069 Disable video recording in Windows due to ffmpeg crash
  integtest.sh
Labels: bug, backport 1.3, backport 2.x

#1070 [2.x] Adding placeholder to keep main/2.x/1.x consistent before #988 backports and disable windows video recording
  integtest.sh
Labels: bug, backport 1.3

#1073 Update tenant to global to maps-dashboards
  cypress/integration/plugins/custom-import-map-dashboards/1_import_vector_map_tab.spec.js
  cypress/integration/plugins/custom-import-map-dashboards/2_opensearchMapLayer.spec.js
  cypress/integration/plugins/custom-import-map-dashboards/3_add_saved_object.spec.js
  cypress/integration/plugins/custom-import-map-dashboards/4_documentsLayer.spec.js
Labels: backport 2.12

#1074 Enable cypress tests to run datagrid table in Discover
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/date_nanos.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/date_nanos_mixed.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/doc_navigation.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/doc_table.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/field_data.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/index_pattern_with_encoded_id.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/index_pattern_without_field.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/large_string.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/saved_queries.spec.js
  cypress/utils/dashboards/data_explorer/commands.js
  cypress/utils/dashboards/data_explorer/index.d.ts
Labels: backport 2.x, backport 2.12

#1085 [2.12] Update security analytics tests
  cypress/integration/plugins/security-analytics-dashboards-plugin/1_detectors.spec.js
  cypress/integration/plugins/security-analytics-dashboards-plugin/2_rules.spec.js
  cypress/integration/plugins/security-analytics-dashboards-plugin/3_alerts.spec.js
  cypress/integration/plugins/security-analytics-dashboards-plugin/4_findings.spec.js
  cypress/utils/plugins/security-analytics-dashboards-plugin/constants.js
  cypress/utils/plugins/security-analytics-dashboards-plugin/helpers.js
Labels: backport 2.x, backport main, v2.12.0

#1088 Fix in-context reporting tests
  cypress/integration/plugins/observability-dashboards/6_notebooks.spec.js
Labels: backport 2.x, backport main, v2.12.0

#1089 Fix reports dashboards test
  cypress/integration/plugins/reports-dashboards/04-download.spec.js
Labels: backport 2.x, backport main, v2.12.0

#1090 Increase delay times in gantt charts
  cypress/integration/plugins/gantt-chart-dashboards/gantt_ui.spec.js
Labels: backport 2.x, backport main, v2.12.0

#1092 Fix query workbench tests
  cypress/integration/plugins/query-workbench-dashboards/ui.spec.js
Labels: backport 2.x, backport main, v2.12.0

#1105 Normalize query workbench constant newlines
  cypress/integration/plugins/query-workbench-dashboards/ui.spec.js
Labels: backport 2.x, backport main

#1093 Increased timeout thresholds for alerting cypress tests to reduce flakiness when running on slow domains.
  cypress/integration/plugins/alerting-dashboards-plugin/acknowledge_alerts_modal_spec.js
  cypress/integration/plugins/alerting-dashboards-plugin/alert_spec.js
  cypress/integration/plugins/alerting-dashboards-plugin/alerts_dashboard_flyout_spec.js
  cypress/integration/plugins/alerting-dashboards-plugin/bucket_level_monitor_spec.js
  cypress/integration/plugins/alerting-dashboards-plugin/cluster_metrics_monitor_spec.js
  cypress/integration/plugins/alerting-dashboards-plugin/composite_level_monitor_spec.js
  cypress/integration/plugins/alerting-dashboards-plugin/document_level_monitor_spec.js
  cypress/integration/plugins/alerting-dashboards-plugin/monitors_dashboard_spec.js
  cypress/integration/plugins/alerting-dashboards-plugin/query_level_monitor_spec.js
  cypress/utils/plugins/alerting-dashboards-plugin/constants.js
Labels: backport 2.x, backport 2.12

#1110 Fix assistant failed cases because of change of ml-commons
  .github/workflows/assistant-release-e2e-workflow.yml
  cypress/integration/plugins/dashboards-assistant/chatbot_interaction_trace_spec.js
  cypress/support/assistant-dummy-llm.js
Labels: backport 2.x

#946 Updated tests for security analytics
  cypress/integration/plugins/security-analytics-dashboards-plugin/1_detectors.spec.js
  cypress/integration/plugins/security-analytics-dashboards-plugin/2_rules.spec.js
  cypress/integration/plugins/security-analytics-dashboards-plugin/3_alerts.spec.js
  cypress/integration/plugins/security-analytics-dashboards-plugin/4_findings.spec.js
  cypress/utils/plugins/security-analytics-dashboards-plugin/constants.js
  cypress/utils/plugins/security-analytics-dashboards-plugin/helpers.js
Labels: backport 2.x, v2.12.0, backport 2.12

#1038 Fix flaky test for vis-augmenter
  .github/workflows/cypress-workflow-bundle-snapshot-based-windows.yml
  .github/workflows/cypress-workflow-bundle-snapshot-based.yml
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis-augmenter/dashboard_spec.js
  cypress/utils/dashboards/vis-augmenter/commands.js
  cypress/utils/dashboards/vis-augmenter/helpers.js
Labels: backport 2.x

#1123 Add download_chromium to integtest.sh for standalone chromium installation
  browser_downloader.sh
  integtest.sh
Labels: enhancement, backport 1.3, backport 2.x, backport 2.12

#1079 fixed failed discover app shared links tests
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/shared_links.spec.js
Labels: backport 2.x
