Repository opensearch-project/opensearch-dashboards-functional-test, pull requests merged in 2024-08, with the labels that each got.

#1449 Fixes the permissions spec and related to fixtures to reflect correct action-group names
  cypress/fixtures/plugins/security/permissions/actiongroups_post_new_creation_from_selection_response.json
  cypress/fixtures/plugins/security/permissions/actiongroups_post_new_creation_response.json
  cypress/integration/plugins/security-dashboards-plugin/sanity_tests.spec.js
  cypress/integration/plugins/security/permissions_spec.js
Labels: backport 2.x, v2.16.0, backport 2.16

#1465 fix tests to work with security enabled
  cypress/integration/plugins/notifications-dashboards/1_email_senders_and_groups.spec.js
Labels: backport 2.x, v2.16.0, backport 2.16

#1469 Fix tests
  cypress/integration/plugins/notifications-dashboards/1_email_senders_and_groups.spec.js
Labels: backport 2.x, backport main, v2.16.0

#1473 Cleanup Index patterns after the test
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/index_pattern_without_field.spec.js
  cypress/utils/dashboards/vis_type_table/table.js
Labels: backport 2.x

#1451 Fixed alerting cypress tests.
  cypress/integration/plugins/alerting-dashboards-plugin/bucket_level_monitor_spec.js
  cypress/integration/plugins/alerting-dashboards-plugin/query_level_monitor_spec.js
Labels: backport 2.x, v2.16.0, backport 2.16

#1468 Remove the old datasource tests for dashboards observability
  cypress/integration/plugins/observability-dashboards/7_datasources_dashboard.spec.js
Labels: backport 2.x, v2.16.0, backport 2.16

#1484 Fix security notifs
  cypress/integration/plugins/notifications-dashboards/1_email_senders_and_groups.spec.js
Labels: backport 2.x, backport main, v2.16.0

#1487 [Maps] Add wait before select layer
  cypress/integration/plugins/custom-import-map-dashboards/4_documentsLayer.spec.js
Labels: backport 2.x, backport 2.16

#1490 Fix Discover Advanced Setting Bug
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover_advanced_settings.spec.js
Labels: backport 2.x, v2.16.0, backport 2.16

#1494 Security notif test
  cypress/integration/plugins/notifications-dashboards/1_email_senders_and_groups.spec.js
Labels: backport 2.x, backport main, v2.16.0

#1491 remove command time out for gantt chart
  cypress/integration/plugins/gantt-chart-dashboards/gantt_ui.spec.js
Labels: backport 2.x, v2.16.0, backport 2.16

#1500 Fixed alerting cypress tests.
  cypress/integration/plugins/alerting-dashboards-plugin/bucket_level_monitor_spec.js
  cypress/integration/plugins/alerting-dashboards-plugin/query_level_monitor_spec.js
Labels: backport 2.x, backport 2.16

#1503 select checkbox via id instead of class name
  cypress/integration/plugins/index-management-dashboards-plugin/aliases.js
Labels: v2.16.0, backport 2.16

#1507 Fix channel tests
  cypress/fixtures/plugins/notifications-dashboards/test_chime_channel.json
  cypress/fixtures/plugins/notifications-dashboards/test_slack_channel.json
  cypress/integration/plugins/notifications-dashboards/2_channels.spec.js
Labels: backport 2.x, backport 2.16

#1520 Fix panel test not respecting base path setting
  cypress/integration/plugins/observability-dashboards/4_panels.spec.js
Labels: backport 2.x

#1523 Security analytics tests - removed test index settings.
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/integration_tests/index/create_dns_settings.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/integration_tests/index/create_windows_settings.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/sample_dns_index_settings.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/sample_network_index_settings.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/sample_windows_index_settings.json
Labels: backport 2.x, backport 2.15, backport 2.16

#1537 Fix Cypress Test Flakiness by Executing cy.visit Before cy.request
  cypress/integration/plugins/anomaly-detection-dashboards-plugin/create_detector_spec.js
  cypress/integration/plugins/anomaly-detection-dashboards-plugin/detector_configuration_spec.js
  cypress/integration/plugins/anomaly-detection-dashboards-plugin/historical_analysis_spec.js
  cypress/integration/plugins/anomaly-detection-dashboards-plugin/overview_spec.js
  cypress/integration/plugins/anomaly-detection-dashboards-plugin/sample_detector_spec.js
  cypress/integration/plugins/anomaly-detection-dashboards-plugin/vis_augmenter/associate_detector_spec.js
  cypress/integration/plugins/anomaly-detection-dashboards-plugin/vis_augmenter/augment_vis_saved_object_spec.js
  cypress/integration/plugins/anomaly-detection-dashboards-plugin/vis_augmenter/view_anomaly_events_spec.js
Labels: backport 2.x
