Repository opensearch-project/opensearch-dashboards-functional-test, pull requests merged in 2024-04, with the labels that each got.

#1119 [Docs] Add developer doc for Orchestrator remote test workflow
  DEVELOPER_GUIDE.md
Labels: documentation, backport 2.x, backport 2.12, v2.13.0

#1199 [Multiple Datasource]Fix failed test cases caused by switching from EuiSelect to EuiSuperSelect
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/datasource-management-plugin/1_create_datasource.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/datasource-management-plugin/3_update_datasource.spec.js
  cypress/utils/dashboards/datasource-management-dashboards-plugin/constants.js
Labels: backport 2.x

#1207 Use global tenant in vis-builder tests
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/basic.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/dashboard.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/experimental.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/area.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/bar.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/line.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/metric.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/table.spec.js
Labels: backport 2.x, v2.14.0

#1209 [OSD] Sanitize copied share-link before validating
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/shared_links.spec.js
Labels: backport 2.x, v2.14.0

#1210 Use global tenant in vis_type_table and other tests
  cypress/integration/common/dashboard_sample_data_spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_table/basic.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_table/data.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_table/embed.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_table/options.spec.js
Labels: backport 2.x

#1232 [Workspace] Clean up workspace after tests and disable multi-tenancy when running workspace test
  .github/workflows/workspace-release-e2e-workflow.yml
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/workspace_create.spec.js
Labels: backport main, v2.14.0

#1217 Delete experimental.spec.js as VisBuilder Advances to Production Stage
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/experimental.spec.js
Labels: backport 2.x, v2.14.0

#1236 Update tenant in reporting tests
  cypress/integration/plugins/reports-dashboards/01-create.spec.js
  cypress/integration/plugins/reports-dashboards/04-download.spec.js
Labels: backport 2.x, v2.14.0

#1238 fix issue code reviewer list doesn't reflect the right code owner list
  .github/CODEOWNERS
Labels: backport 2.x

#1229 Add test cases for Admin UI MDS
  .github/workflows/ml-commons-release-e2e-workflow.yml
  cypress/integration/plugins/ml-commons-dashboards/1_overview_spec.js
  cypress/integration/plugins/ml-commons-dashboards/2_overview_remote_model_spec.js
  cypress/integration/plugins/ml-commons-dashboards/overview_spec.js
  cypress/utils/commands.js
  cypress/utils/plugins/ml-commons-dashboards/commands.js
  cypress/utils/plugins/ml-commons-dashboards/constants.js
Labels: backport 2.x, v2.14.0

#1221 [Workspace] Add functional tests for create/update workspace page
  .github/workflows/workspace-release-e2e-workflow.yml
  cypress.json
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/workspace_create.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/workspace_update.spec.js
  cypress/support/index.js
  cypress/utils/dashboards/workspace-plugin/commands.js
  cypress/utils/dashboards/workspace-plugin/constants.js
Labels: backport 2.x, v2.14.0

#1228 [Workspace] add tests for workspace dropdown menu
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/workspace_dropdown_menu.spec.js
  cypress/utils/dashboards/workspace-plugin/commands.js
Labels: backport 2.x, v2.14.0

#1247 Update test name in results site
  site/js/dashboard.js
Labels: backport 2.x, v2.14.0

#1250 Use moveToTestNotebook during notebooks-reporting integration suite
  cypress/integration/plugins/observability-dashboards/6_notebooks.spec.js
Labels: backport 2.x, v2.14.0

#1253 Increase jvm_heap_memory_threshold to 100 for ml-commons dashboards
  cypress/utils/plugins/ml-commons-dashboards/commands.js
Labels: backport 2.x, v2.14.0

#1246 [Workspace] Add functional test for workspace overview page
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/workspace_create.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/workspace_dropdown_menu.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/workspace_overview.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/workspace_update.spec.js
  cypress/utils/dashboards/workspace-plugin/commands.js
Labels: backport 2.x, v2.14.0

#1182 Add Discover Table Tests
  cypress/fixtures/dashboard/opensearch_dashboards/data_explorer/index_with_nested_field/data.json.txt
  cypress/fixtures/dashboard/opensearch_dashboards/data_explorer/index_with_nested_field/mappings.json.txt
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover_advanced_settings.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover_table.spec.js
  cypress/utils/dashboards/data_explorer/commands.js
Labels: backport 2.x, v2.14.0

#1257 Update getDetectors URL to match recent API changes
  cypress/utils/plugins/anomaly-detection-dashboards-plugin/constants.js
Labels: backport 2.x, v2.14.0, backport 2.14
