Repository opensearch-project/opensearch-dashboards-functional-test, pull requests merged in 2024-06, with the labels that each got.

#1345 Separate ml-commons-dashboards MDS cases
  .github/workflows/ml-commons-release-e2e-workflow.yml
  cypress/integration/plugins/ml-commons-dashboards/1_overview_spec.js
  cypress/integration/plugins/ml-commons-dashboards/2_overview_remote_model_spec.js
  cypress/integration/plugins/ml-commons-dashboards/mds_1_overview_spec.js
  cypress/integration/plugins/ml-commons-dashboards/mds_2_overview_remote_model_spec.js
  cypress/utils/plugins/ml-commons-dashboards/shared/overview.js
Labels: backport 2.x, v2.15.0

#1340 Add Test for Vis Builder Bugs
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/basic.spec.js
Labels: backport 2.x, v2.15.0

#1341 [MDS] add workspace tests with multiple data source enabled
  .github/workflows/workspace-release-e2e-workflow.yml
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_create.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_dropdown_menu.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_overview.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_update.spec.js
Labels: backport 2.x, v2.15.0

#1343 [MDS] Add FT for Timeline
  cypress/fixtures/dashboard/opensearch_dashboards/vis_type_timeline/vis-timeline.data.txt
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_timeline/mds_timeline.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_timeline/timeline.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_timeline/utils.js
  cypress/utils/dashboards/commands.js
  cypress/utils/dashboards/constants.js
  cypress/utils/dashboards/vis_type_timeline/commands.js
  cypress/utils/dashboards/vis_type_timeline/constants.js
Labels: backport 2.x, v2.15.0

#1339 [MDS]add commands to for seletable and aggregated view
  cypress/utils/commands.js
  cypress/utils/dashboards/datasource-management-dashboards-plugin/commands.js
  cypress/utils/dashboards/datasource-management-dashboards-plugin/constants.js
Labels: backport 2.x, v2.15.0

#1358 Don't need to force DatePickerMenu open
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover.spec.js
  cypress/utils/dashboards/data_explorer/commands.js
  cypress/utils/dashboards/data_explorer/index.d.ts
Labels: backport 2.x, v2.15.0

#1352 [Infra] Add CI groups for OSD core test cases to avoid flaky test
  .github/workflows/cypress-workflow-bundle-snapshot-based-ci-groups.yml
  .github/workflows/cypress-workflow-bundle-snapshot-based-windows.yml
  .github/workflows/cypress-workflow-bundle-snapshot-based.yml
  .github/workflows/mds-release-e2e-workflow.yml
Labels: backport main, v2.15.0

#1267 Add functional test for UI Metric
  .github/workflows/cypress-workflow-bundle-snapshot-based.yml
  cypress.json
  cypress/fixtures/dashboard/opensearch_dashboards/telemetry/uiReport.json
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/telemetry/server.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/telemetry/ui_metric.spec.js
  package.json
Labels: backport 2.x, v2.15.0

#1372 Set dashboards admin for security enabled tests
  .github/workflows/workspace-release-e2e-workflow.yml
Labels: backport main, v2.15.0

#1376 Trace analytics cypress update for 2.15
  cypress/integration/plugins/observability-dashboards/1_trace_analytics_dashboard.spec.js
  cypress/integration/plugins/observability-dashboards/2_trace_analytics_services.spec.js
Labels: backport 2.x, v2.15.0

#1377 Fix Flaky Discover Table Tests
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover_table.spec.js
Labels: backport 2.x

#1371 Fix flaky tests in core dashboard.
  .github/workflows/cypress-workflow-bundle-snapshot-based-ci-groups.yml
  .github/workflows/cypress-workflow-bundle-snapshot-based.yml
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover_advanced_settings.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover_histogram.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover_table.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/shared_links.spec.js
  cypress/utils/commands.js
Labels: backport main, v2.15.0

#1375 Update workspace description usecase tests
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/workspace_create.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/workspace_dropdown_menu.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/workspace_overview.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/workspace_update.spec.js
Labels: backport main, v2.15.0

#1374 [MDS] Add dashboard assistant tests with multiple data source enabled
  .github/workflows/assistant-release-e2e-workflow.yml
  cypress/integration/plugins/dashboards-assistant/mds_chatbot_agent_framework_spec.js
  cypress/integration/plugins/dashboards-assistant/mds_chatbot_interaction_trace_spec.js
  cypress/integration/plugins/dashboards-assistant/mds_chatbot_sidecar_spec.js
  cypress/integration/plugins/dashboards-assistant/mds_conversation_history_spec.js
  cypress/integration/plugins/dashboards-assistant/mds_feedback_spec.js
  cypress/support/index.js
  cypress/utils/dashboards/datasource-management-dashboards-plugin/commands.js
  cypress/utils/plugins/dashboards-assistant/commands.js
Labels: backport main, v2.15.0

#1357 [Workspace]Add workspace import sample data cases
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_import_sample_data_to.spec.js
  cypress/utils/commands.js
Labels: backport 2.x, v2.15.0

#1383 fix data source flaky tests
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/datasource-management-plugin/1_create_datasource.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/datasource-management-plugin/2_datasource_table.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/datasource-management-plugin/3_update_datasource.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/datasource-management-plugin/4_set_default_datasource.spec.js
  cypress/utils/dashboards/datasource-management-dashboards-plugin/commands.js
Labels: backport main, v2.15.0, backport 2.15

#1399 [Security Analytics][2.15] Update tests for PR 1014 in Security Analytics Dashboards
  cypress/integration/plugins/security-analytics-dashboards-plugin/3_alerts.spec.js
Labels: v2.15.0

#1402 [Security Analytics][2.15] Fix alerts tests security analytics
  cypress/integration/plugins/security-analytics-dashboards-plugin/3_alerts.spec.js
Labels: backport 2.x, backport main, v2.15.0

#1386 Add chatbot test cases for default data source change
  cypress/integration/plugins/dashboards-assistant/mds_chatbot_default_data_source_change.js
  cypress/utils/dashboards/datasource-management-dashboards-plugin/commands.js
Labels: backport 2.x, v2.15.0, backport 2.15

#1412 Add functional test for version decouple
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/datasource-management-plugin/5_version_decouple.spec.js
Labels: backport 2.x, v2.16.0

#1414 [Security analytics][2.15] Wait for alerts to load completely before checking
  cypress/integration/plugins/security-analytics-dashboards-plugin/3_alerts.spec.js
Labels: backport 2.x, backport main, v2.15.0

#1408 feat: freeze browser version to 112
  .github/workflows/cypress-workflow-bundle-snapshot-based-ci-groups.yml
  .github/workflows/cypress-workflow-bundle-snapshot-based-windows.yml
  .github/workflows/cypress-workflow-bundle-snapshot-based.yml
  .github/workflows/release-e2e-workflow-template.yml
  cypress.json
  cypress/support/index.js
Labels: backport main, v2.15.0, backport 2.15

#1411 feat: reuse specs finder
  .github/workflows/cypress-workflow-bundle-snapshot-based-ci-groups.yml
  test_finder.sh
Labels: backport 2.x, backport main, v2.15.0

#1432 Resolve multiple OSD core test issues observed in 2.15.0
  .gitattributes
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_table/embed.spec.js
  integtest.sh
  package.json
Labels: backport 2.x, release, backport main, v2.15.0

#1436 [Backport main] Resolve multiple OSD core test issues observed in 2.15.0 (#1432)
  .gitattributes
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_table/embed.spec.js
  integtest.sh
  package.json
Labels: release, v2.15.0
