Repository opensearch-project/opensearch-dashboards-functional-test, pull requests merged in 2024-05, with the labels that each got.

#1260 [MD] Replace fake data source endpoint with configurable real endpoint
  .github/workflows/cypress-workflow-bundle-snapshot-based.yml
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/datasource-management-plugin/1_create_datasource.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/datasource-management-plugin/2_datasource_table.spec.js
  cypress/utils/dashboards/datasource-management-dashboards-plugin/commands.js
  cypress/utils/dashboards/datasource-management-dashboards-plugin/constants.js
Labels: backport 2.x, v2.15.0

#1272 Move Intercept in Observability Panels Test
  cypress/integration/plugins/observability-dashboards/4_panels.spec.js
Labels: backport 2.x, v2.14.0, backport 2.14

#1284 Updated security analytics cypress tests.
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/integration_tests/rule/create_windows_usb_rule.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/sample_document.json
  cypress/fixtures/plugins/security-analytics-dashboards-plugin/sample_windows_index_settings.json
  cypress/integration/plugins/security-analytics-dashboards-plugin/2_rules.spec.js
  cypress/integration/plugins/security-analytics-dashboards-plugin/3_alerts.spec.js
Labels: backport 2.x, backport 2.13, backport 2.14

#1280 Fix: flaky test on 2.14
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/aaa_before.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover_advanced_settings.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/index_pattern_without_field.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/shared_links.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis-augmenter/dashboard_spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/basic.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/dashboard.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/area.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/bar.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/line.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/metric.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/table.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_table/basic.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_table/data.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_table/embed.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_table/options.spec.js
  cypress/utils/commands.js
Labels: backport 2.x, v2.14.0, backport 2.14

#1291 feat: only flesh tenant when security enabled
  cypress/utils/commands.js
Labels: backport 2.x, v2.14.0, backport 2.14

#1294 Fixed security analytics cypress test.
  cypress/integration/plugins/security-analytics-dashboards-plugin/3_alerts.spec.js
Labels: backport 2.x, v2.14.0, backport 2.14

#1302 Fix Test Failures
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover_advanced_settings.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover_table.spec.js
  cypress/utils/commands.js
Labels: backport 2.x, backport main, v2.14.0

#1297 [Enhancement] Skip datasources tests for managed service run
  cypress/integration/plugins/observability-dashboards/7_datasources_dashboard.spec.js
Labels: backport 2.x, v2.13.0, backport 2.13, v2.14.0, backport 2.14

#1311 [Security Analytics] Updated alerts spec for the security analytics PR 1010
  cypress/integration/plugins/security-analytics-dashboards-plugin/3_alerts.spec.js
Labels: backport 2.x, backport 2.14

#1314 fix: use lightweight way to flesh tenant settings
  cypress/utils/commands.js
  cypress/utils/dashboards/commands.js
Labels: backport 2.x, v2.14.0, backport 2.14

#1315 Navigate directly to discover to reduce flakiness
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/dashboard_share_copy_link_test.js
Labels: backport 2.x, backport main

#1318 fix: defaultTenant does not take effect
  cypress/utils/commands.js
  cypress/utils/dashboards/commands.js
Labels: bug, backport 2.x, v2.14.0, backport 2.14

#1321 Fix: test failures related to saved objects(tenant)
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover_advanced_settings.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/index_pattern_without_field.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/shared_links.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/basic.spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/dashboard.spec.js
  cypress/integration/plugins/gantt-chart-dashboards/gantt_ui.spec.js
Labels: backport 2.x, v2.14.0, backport 2.14

#1330 [MDS] add dashboards sanity tests with multiple data source enabled
  .github/workflows/cypress-workflow-bundle-snapshot-based.yml
  cypress.json
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/dashboard_sample_data_with_datasource_spec.js
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/mds_dashboard_sanity_test_spec.js
  cypress/utils/commands.js
Labels: backport 2.x, v2.15.0

#1331 Updating security reachout email
  SECURITY.md
Labels: backport 2.x, v2.15.0
