Repository opensearch-project/opensearch-dashboards-functional-test, pull requests merged in 2024-09, with the labels that each got.

#1546 [Backport 2.x]Bump JDK to 21 (#1384)
  .github/actions/start-opensearch/action.yml
  .github/workflows/cypress-workflow-bundle-snapshot-based-ci-groups.yml
  .github/workflows/release-e2e-workflow-template-windows.yml
  .github/workflows/release-e2e-workflow-template.yml
Labels: backport 2.17

#1548 Fix Flaky Discover Tests
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover_advanced_settings.spec.js
Labels: backport 2.x, backport 2.17

#1558 [2.17][Security analytics] Bypass element overlap when typing
  cypress/integration/plugins/security-analytics-dashboards-plugin/2_rules.spec.js
Labels: backport 2.x, backport main

#1569 Fixes ISM cypress failures due to missing admin certificates
  cypress.json
  cypress/resources/kirk-key.pem
  cypress/resources/kirk.pem
  cypress/resources/root-ca.pem
  cypress/utils/plugins/index-management-dashboards-plugin/commands.js
Labels: backport main, backport 2.17

#1572 Fix Alerts SA tests
  cypress/integration/plugins/security-analytics-dashboards-plugin/3_alerts.spec.js
Labels: backport 2.x, v2.17.0, backport 2.17
