Repository opensearch-project/opensearch-dashboards-functional-test, pull requests merged in 2024-10, with the labels that each got.

#1587 [Maps plugin] Skip new home UI test if disabled in OSD
  cypress/integration/plugins/custom-import-map-dashboards/7_enable_new_home_ui.spec.js
Labels: backport 2.x, backport 2.17

#1586 Adding Flow Framework Dashboards integration tests
  .github/workflows/dashboards-flow-framework-e2e-workflow.yml
  cypress/fixtures/plugins/dashboards-flow-framework/create_connector.json
  cypress/fixtures/plugins/dashboards-flow-framework/register_model.json
  cypress/fixtures/plugins/dashboards-flow-framework/semantic_search/import_workflow.json
  cypress/fixtures/plugins/dashboards-flow-framework/semantic_search/ingest_response.json
  cypress/fixtures/plugins/dashboards-flow-framework/semantic_search/search_query.json
  cypress/fixtures/plugins/dashboards-flow-framework/semantic_search/search_response.json
  cypress/fixtures/plugins/dashboards-flow-framework/semantic_search/source_data.json
  cypress/integration/plugins/dashboards-flow-framework/create_workflow_spec.js
  cypress/support/index.js
  cypress/utils/commands.js
  cypress/utils/constants.js
  cypress/utils/plugins/dashboards-flow-framework/commands.js
  cypress/utils/plugins/dashboards-flow-framework/constants.js
  cypress/utils/plugins/dashboards-flow-framework/helpers.js
  site/index.html
  site/js/dashboard.js
  test_finder.sh
Labels: backport 2.x

#1601 Clean query to make the test more robust
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover.spec.js
  cypress/utils/dashboards/commands.js
Labels: backport 2.x, v2.18.0

#1578 [Alerting dashboards] Update alerting dashboard tests due to fit and finish changes
  cypress/integration/plugins/alerting-dashboards-plugin/bucket_level_monitor_spec.js
  cypress/integration/plugins/alerting-dashboards-plugin/cluster_metrics_monitor_spec.js
  cypress/integration/plugins/alerting-dashboards-plugin/composite_level_monitor_spec.js
  cypress/integration/plugins/alerting-dashboards-plugin/document_level_monitor_spec.js
  cypress/integration/plugins/alerting-dashboards-plugin/query_level_monitor_spec.js
Labels: backport 2.x
