Repository opensearch-project/opensearch-dashboards-functional-test, pull requests merged in 2025-01, with the labels that each got.

#1671 Improve workspace import sample data tests
  .github/workflows/cypress-workflow-bundle-snapshot-based.yml
  cypress/utils/dashboards/workspace-plugin/test-cases/mds_workspace_import_sample_data_to.cases.js
Labels: backport 2.x

#1673 [Workspace] add copy functional tests
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_copy.spec.js
  cypress/utils/dashboards/workspace-plugin/test-cases/mds_workspace_copy.cases.js
Labels: backport 2.x

#1669 Update observability dashboards tests
  cypress/integration/plugins/observability-dashboards/2_trace_analytics_services.spec.js
  cypress/integration/plugins/observability-dashboards/3_trace_analytics_traces.spec.js
  cypress/integration/plugins/observability-dashboards/6_notebooks.spec.js
  cypress/utils/plugins/observability-dashboards/constants.js
Labels: backport 2.x

#1677 Fix shared link test in 2.x for 2.19
  cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/shared_links.spec.js
Labels: v2.19.0

#1678 Update Flow Framework tests
  cypress/integration/plugins/dashboards-flow-framework/create_workflow_spec.js
Labels: backport 2.x, v2.19.0

#1682 Update Flow Framework Tests cont.
  cypress/integration/plugins/dashboards-flow-framework/create_workflow_spec.js
Labels: backport 2.x, v2.19.0, backport 2.19

#1683 [CVE-2024-21538] Bump cross-spawn to 7.0.5
  package-lock.json
  package.json
Labels: backport 2.x, v2.19.0, backport 2.19
