Repository opensearch-project/opensearch-dashboards-functional-test, pull requests merged in 2025-08, with the labels that each got.

#1828 Ensure windows install cypress based on ci bucket source
  integtest.sh
Labels: enhancement, dependencies, windows, release, backport 2.19, v3.2.0, backport 3.2

#1823 extract tenant-dialog helper & improve forecaster list test robustness
  cypress/integration/plugins/anomaly-detection-dashboards-plugin/forecaster_list_spec.js
  cypress/utils/plugins/anomaly-detection-dashboards-plugin/commands.js
Labels: backport 3.1, backport 3.2

#1835 test: improve resilience in forecast tests
  cypress/integration/plugins/anomaly-detection-dashboards-plugin/daily_forecaster_spec.js
  cypress/integration/plugins/anomaly-detection-dashboards-plugin/forecaster_list_spec.js
  cypress/integration/plugins/anomaly-detection-dashboards-plugin/forecaster_list_spec_mock.js
  cypress/utils/plugins/anomaly-detection-dashboards-plugin/commands.js
Labels: backport 3.2

#1839 Fix test hang on tenant selection dialog
  cypress/integration/plugins/anomaly-detection-dashboards-plugin/forecaster_list_spec.js
Labels: v3.2.0, backport 3.2

#1841 updated the window size -QueryInsights Dashboards
  cypress/utils/plugins/query-insights-dashboards/commands.js
Labels: v3.2.0, backport 3.2
