Repository opensearch-project/opensearch-dashboards-functional-test, pull requests merged in 2025-02, with the labels that each got.

#1689 Onboard query insights dashboards onto functional test repo
  .github/workflows/query-insights-dashboards-e2e-workflow.yml
  cypress/fixtures/plugins/query-insights-dashboards/sample_document.json
  cypress/integration/plugins/query-insights-dashboards/1_top_queries.cy.js
  cypress/integration/plugins/query-insights-dashboards/2_query_details.cy.js
  cypress/integration/plugins/query-insights-dashboards/3_configurations.cy.js
  cypress/support/index.js
  cypress/utils/constants.js
  cypress/utils/plugins/query-insights-dashboards/commands.js
  cypress/utils/plugins/query-insights-dashboards/constants.js
  site/index.html
  site/js/dashboard.js
  test_finder.sh
Labels: backport 2.x, backport 2.19

#1693 Update notebooks and traces tests with dynamic wait
  cypress/integration/plugins/observability-dashboards/2_trace_analytics_services.spec.js
  cypress/integration/plugins/observability-dashboards/6_notebooks.spec.js
Labels: backport 2.x, backport main

#1697 Update notebooks test with delay for delete
  cypress/integration/plugins/observability-dashboards/6_notebooks.spec.js
Labels: backport 2.x, backport main

#1696 Update FF test to integrate with new API calls
  cypress/fixtures/plugins/dashboards-flow-framework/semantic_search/import_workflow.json
  cypress/fixtures/plugins/dashboards-flow-framework/semantic_search/simulate_pipeline_response.json
  cypress/integration/plugins/dashboards-flow-framework/create_workflow_spec.js
  cypress/utils/plugins/dashboards-flow-framework/commands.js
Labels: backport 2.x

#1701 Fixing couple of flaky tests in rollups and transforms
  cypress/integration/plugins/index-management-dashboards-plugin/rollups_spec.js
  cypress/integration/plugins/index-management-dashboards-plugin/transforms_spec.js
Labels: backport 2.x, backport 2.19

#1713 [Flow Framework] Add containsModels param to handle custom/empty template
  cypress/integration/plugins/dashboards-flow-framework/create_workflow_spec.js
Labels: backport 2.x

#1722 [Bug]Updated flakey test from reporting homepage
  .github/workflows/release-e2e-workflow-template.yml
  cypress/integration/plugins/reports-dashboards/04-download.spec.js
Labels: backport 2.3, backport 2.5, backport 2.7

#1725 Update flaky observability panels tests
  cypress/integration/plugins/observability-dashboards/4_panels.spec.js
Labels: backport 2.7

#1732 [Flow Framework] Update sample input to JSON lines format
  cypress/fixtures/plugins/dashboards-flow-framework/semantic_search/source_data.json
  cypress/fixtures/plugins/dashboards-flow-framework/semantic_search/source_data.jsonl
  cypress/integration/plugins/dashboards-flow-framework/create_workflow_spec.js
Labels: backport 2.x
