Repository opensearch-project/opensearch-dashboards-functional-test, pull requests merged in 2025-04, with the labels that each got.

#1764 Fix Integration test
  .github/workflows/assistant-release-e2e-workflow.yml
  .github/workflows/release-e2e-workflow-template.yml
  cypress/fixtures/plugins/dashboards-assistant/agent-framework-thought-response.json
  cypress/fixtures/plugins/dashboards-assistant/flow-template.json
  cypress/integration/plugins/dashboards-assistant/conversation_save_to_notebook_spec.js
  cypress/integration/plugins/dashboards-assistant/mds_chatbot_agent_framework_spec.js
  cypress/integration/plugins/dashboards-assistant/mds_chatbot_default_data_source_change.js
  cypress/integration/plugins/dashboards-assistant/mds_chatbot_interaction_trace_spec.js
  cypress/integration/plugins/dashboards-assistant/mds_chatbot_sidecar_spec.js
  cypress/integration/plugins/dashboards-assistant/mds_conversation_history_spec.js
  cypress/integration/plugins/dashboards-assistant/mds_feedback_spec.js
  cypress/support/assistant-dummy-llm.js
Labels: backport 3.0

#1772 Feat add tests for t2v
  .github/workflows/assistant-release-e2e-workflow.yml
  cypress/fixtures/plugins/dashboards-assistant/flow-templates/chat.json
  cypress/fixtures/plugins/dashboards-assistant/flow-templates/query-assist-ppl.json
  cypress/fixtures/plugins/dashboards-assistant/flow-templates/text2vega-with-instructions.json
  cypress/fixtures/plugins/dashboards-assistant/flow-templates/text2vega.json
  cypress/fixtures/plugins/dashboards-assistant/query-assist-ppl-response.json
  cypress/fixtures/plugins/dashboards-assistant/text2vega-response.json
  cypress/fixtures/plugins/dashboards-assistant/text2vega-with-instructions-response.json
  cypress/integration/plugins/dashboards-assistant/conversation_chatbot_save_to_notebook_spec.js
  cypress/integration/plugins/dashboards-assistant/mds_chatbot_conversation_history_spec.js
  cypress/integration/plugins/dashboards-assistant/mds_chatbot_feedback_spec.js
  cypress/integration/plugins/dashboards-assistant/mds_query_enhancements_t2v_spec.js
  cypress/support/assistant-dummy-llm.js
  cypress/support/index.js
  cypress/utils/plugins/dashboards-assistant/commands.js
  cypress/utils/plugins/dashboards-assistant/constants.js
Labels: v3.0.0

#1776 ReportingDashboard - Test fix
  cypress/integration/plugins/reports-dashboards/04-download.spec.js
Labels: backport 3.0

#1782 Feat: add tests for alert summary, discovery summary and anonymous detect
  .github/workflows/assistant-release-e2e-workflow.yml
  cypress/fixtures/plugins/alerting-dashboards-plugin/sample_query_level_monitor_for_alert_summary.json
  cypress/fixtures/plugins/dashboards-assistant/data2summary-response.json
  cypress/fixtures/plugins/dashboards-assistant/flow-templates/data2summary.json
  cypress/fixtures/plugins/dashboards-assistant/flow-templates/suggest-ad.json
  cypress/fixtures/plugins/dashboards-assistant/flow-templates/summary.json
  cypress/fixtures/plugins/dashboards-assistant/flow-templates/summary_with_log_pattern.json
  cypress/fixtures/plugins/dashboards-assistant/suggest-ad-response.json
  cypress/fixtures/plugins/dashboards-assistant/summary-response.json
  cypress/fixtures/plugins/dashboards-assistant/summary-with-log-pattern-response.json
  cypress/integration/plugins/dashboards-assistant/mds_query_enhancements_alert_summary_spec.js
  cypress/integration/plugins/dashboards-assistant/mds_query_enhancements_data2summary_spec.js
  cypress/integration/plugins/dashboards-assistant/mds_query_enhancements_suggest_anomaly_detector_spec.js
  cypress/support/assistant-dummy-llm.js
  cypress/utils/plugins/alerting-dashboards-plugin/commands.js
  cypress/utils/plugins/dashboards-assistant/commands.js
  cypress/utils/plugins/dashboards-assistant/constants.js
Labels: backport main
